#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: anime lycoris
#+hugo_categories: anime
#+hugo_draft: false
#+description: Lycoris Recoil 的影评
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :show_comments true
:END:
#+author: Dantezy
#+date: 2022-09-27
#+TITLE: 不要偷懒
* 缘起
这个标题来自脱口秀演员 Storm Xu 的播客2022年9月11日那一期《【脱口秀大会】能不能四年办一次》。
他在里面批评笑果的演员用太多内部梗，太偷懒了。

我很喜欢 Lycoris 这部动画，如果不是那么喜欢，也不至于写一篇长评。写评论虽然比不上搞创作，
但还是不能偷懒。如果要评论就认真评论，不要凭着喜恶来发泄情绪。
* 总体评价
我最后给 Lycoris 动画打分是5分制的3.8分。在我的标准里面5分是神作，4分非常优秀，3分是平庸之作，
2分基本就是我能忍住看完的下限（虽然往往看不完），1分是完全看不下去。Lycoris 不算很平庸，不过缺点也非常多，
但是很多缺点我都能忍受（除了有一点我后面会说）。

总的感觉就好像看《高达 Seed》（我也很喜欢），商业元素结合得很好，人物也很讨喜，但评价一部动画的多个维度，
没有哪个维度做到极致，如果要做神作，起码要有些地方做到极致才行。
* 缺点
先来谈谈缺点。

1. 画面。怎么说好呢，我不是特别看重画面那一类人（所以我不会对着《紫罗兰永恒花园》说“啊这光这水”），但让我都看得出画面有问题，
   那就真的有问题了。比如第5话里面，千泷带人游玩东京，很多个镜头里面背景的人物（见15:05）就是静止不动的。
   又比如12画，千泷躺在地上休息的时候，两个人都成了豆豆眼。
2. 猥琐的第四话。我很不明白日本人对内裤的执着，这从《龙珠》《蜡笔小新》时代就开始，一直延续到现在。我都想不到有啥可以说的了。
3. 逻辑问题。不要在这个时候引用阿虚的名言（这就是偷懒）。所有作品都可以挑出逻辑的问题，但有一些逻辑会影响到整个作品。
   比如说 DA 居然可以从头吃瘪到尾，我很难想象这是一个秘密机关的水平。这些逻辑问题大部分只是影响观感，大部分我都忍了，
   比如第12话，千束放着女保镖跟还在挣扎爬上来的泷奈不管，跑回去看吉松，这多少有点说不过去了呀。还有最后一话，
   千束打碎玻璃要跟真岛天地同寿这一段，我真的接受不了。人姑娘前十二话甚至愿意为不杀人牺牲自己，怎么最后一话就魔心开杀了呢？
   还是说千束觉得只要不是自己射杀的就不算自己杀人算地心引力杀的？真岛种种大难不死也是很离谱（不过我能忍受）。

我去微博翻了翻评价，有些评论那么多缺点都不在话下，反而是最后千束跟真岛喝瓶饮料让他们受不了，这是何必呢？大家出来二次元混，
谁还每个惺惺相惜的对头。
* 优点
当然 Lycoris 还是有很多优点的，比如说 Lilybell 在第六话10:47的时候就被千束提及，这也解答了我当时的疑问：Lycoris 都是女性孤儿，
那男性孤儿去哪里了？还有真岛的能力，在前面也给出了足够多的耳部特写。这种小细节丰富了作品，比尾田画到后来才加霸气设定和尼卡果实设定合理得多
（当然难度不可同日而语，篇幅摆在那里）。

Lycoris 可以这么火，离不开它造梗的能力，片头的击股之交，第一话描边枪法，当然少不了经典的 Sa~ka~na~.这种梗，很方便传播。加上一个好玩的设定 ——
美少女特工，还有大量的百合情节。

不过话说回来，不是堆满卖点就是好作品——甚至恰恰相反，因为要迎合消费市场，要堆卖点，反而削弱了作品。举个反例就是《女子高中生的虚度日常》，
这部动画就是先给角色贴一个标签，然后让角色去演绎整个标签，整一个以标签为中心（可能后面有改善，因为我看不下去）。

Lycoris 起码成功地塑造了人物（瑞希和胡桃可能是最失败的两个）。泷奈不用说，她逐渐从 DA 的工具，回到一个真正的人，她的改变其来有自，而且有目共睹。
其他角色像风希，出场时间不多，但是勾勒得很充分。第三集千束把泷奈举起来，她救了泷奈，倒数第三集泷奈从天而降，千束被泷奈救回来。这个对称我觉得也挺有意思。

把一部动画看作文化商品不是一个问题，但动画终究还是手艺活，不是堆卖点就能卖出去的。Lycoris 就算时道家常菜，那也是王刚级别的家常菜。
* 总结
其实写这么一篇动画评论，没啥用。影响不了销量也影响不了评价。某种意义上就是一篇“只堪自愉悦”的东西。

但我还是想说，不要偷懒。喜欢讨厌都是自己的事情，如果要评论就要动脑子，要想请楚作品的好坏。这样评论才稍微有那么一丁点的意义。
