#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: anime ghostintheshell
#+hugo_categories: anime
#+hugo_draft: false
#+description: 重新看了一遍 Ghost in the Shell 有一些新的胡思乱想。
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :show_comments true
:END:
#+author: Dantezy
#+date: 2022-10-25
#+TITLE: 再看 Ghost in the Shell
2017年看过一次电影，当时在电脑上看，看得并不认真。10月16日去电影院重新看了一遍，有点新想法。
* 「我」的问题
Ghost in the Shell 纠结的归根到底是「我」的问题：如果记忆被篡改，「我」还是「我」吗？

看到垃圾工人被追那段，我想，按照笛卡尔的观点「我思考所以我存在」，即使记忆被篡改了，只要「我思考」，那「我」依然存在。「我」依然是「我」。

看到傀儡师跟素子融合那段，我觉得笛卡尔的观点只能解决「我」的存在性，无法解决「我」的同一性——就是说「我」是不是原来那个「我」。

这次看的是英文字幕，最后傀儡师用了 merge 这个词，我不能不想到 git repo 。
* git repo 的比喻
假如把「我」看作一个 git repo。

一个 repo ， 姑且命名为 amiya 吧，假如 amiya 本来是一个文本编辑器，但是经过十年迭代，amiya 变成了一个浏览器，那么 amiya 还是同一个 repo 吗？
假如 amiya 不是经过长期迭代从文本编辑器演变成浏览器，而是突然接受一个大 PR ，那 amiya 还是同一个 repo 吗？

回到电影的话，最后傀儡师跟素子的融合就是后面合并大 PR 的情况。回到现实的话，我们都知道人的想法是会变的，在没有记忆篡改技术的今天，一个28岁人的想法跟8岁的自己截然不同，
但这种情况不会有人觉得这个人不再是同一个人。

我的朋友 [[https://reorx.com/][reorx]] 说这个简单，看 repo 的唯一 id，这当然是一个合法解。毕竟当下我们也是靠个人证件证实个人身份，以后可能还会上基因签名——假如有这么一天，要考虑的就是如果到处都是克隆人怎么办。

我想的其实是，一个 repo 其实会引入对其他 repo 的依赖，也会被其他 repo 依赖，忽然的大变动会打破这种依赖。这个比喻就是说一个人的社会关系可以界定「我」，
正常情况下「我」的改变也会伴随着社会关系的改变。但是一个人短时间内彻底的改变会导致社会关系的断裂。

但无论是 Id，还是社会关系，都是通过外部条件来确定「我」。这些都不是很牢固，如果我是一个离群索居的人，那随时可能有个人杀了我，拿走我的身份证，然后以我的身份活下去。

不过真有这种事发生，那「我」不「我」的，也没所谓了。
