#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: log
#+hugo_categories: log
#+hugo_draft: false
#+description: 3月底回了趟家，有些有趣的观察和感想。
#+author: Dantezy
#+date: 2023-04-30
#+TITLE: 回乡偶书2023
* 去机场
为了省钱，我买了酷航凌晨5点出发的票。这个时间睡觉也太尴尬了。于是我干脆11点半就出发坐地铁。
谁曾想人算不如天算（其实是没有查地铁运营时间），到 Tanah Merah 之后去机场的线路已经收档。
于是我出了地铁，想找公交或者打的。路上有几个印裔（至少看上去是印裔，或者是斯里兰卡裔？我分不清）跟我搭讪，
看起来想让我坐他们的车去机场。然后我拦了一辆的士。

路上的士大哥跟我一番吐槽，突出一个保守，他先抱怨政府不应该开放35岁单身买房，导致现在婚育律这么地。
然后话题转回他儿子身上。我力劝他不要被 IT  行业的回光返照骗到，让他儿子读个数学或者物理。

因为到机场太早，航班的登机口还没有定，登机牌就一张纸，我都怕它掉了。我转了一圈，找了个比较舒服的位置开始玩 switch.
回来之前我买了个《星之卡比探索发现》。
* 回罗定
酷航的航班非常无聊（180新币的票还咋样），更要命的是 switch 没电了。幸好只是四小时，加上一夜无眠。这次没有带上 Kindle
或者 Boox 真是失策。

航班降落广州，当时的温度虽然凉了一点，但是我穿了一件外套，也还可以接受。出发前买好了手机的流量包（还有翻墙的流量），
不至于落地失联。不过比较要命的是，因为种种原因，陪伴我十多年的广州号被销号[fn:1]了。

落地首先找 Alex 吃顿饭，跟他穿街过巷吃牛肉面和牛杂，现在想想真是明智的选择。本来计划四月在深圳工作的周末再过去广州找他的，
但是那个计划没有实施（因为那个周末都约深圳的朋友了）。

吃完牛杂又下雨了，去公园前二次元基地逛了一下，直接回老家。在广州省站买票的时候发现一楼已经取消了售票窗口，
只剩下自动售票机。所以不要害怕 AI 会让人失业，任何可以机械化自动化的领域，人类都可能失业。
* 漫长的假期
刚好是清明时节，回家路上堵车好几次。更过分的是客车上在播放一部弱智到难以忍受的电影。

回到家快7点了，罗定比广州冷很多。在广州穿两件衣服勉强可以，回到罗定两件衣服直打哆嗦。我让我爸上去接我的时候顺便带件外套。

我爸只开了我妈以前那台摩托，一个明智的选择。回家的路因为基建和周末放学，比高速更堵，如果开他的汽车，那我们还得在路上堵半个小时。
* 深圳是一个大工地
* 回新加坡
* Footnotes

[fn:1] 应该是因为在新加坡那张 sim 卡一直用不了，连充值都充不上，所以就欠费停机销号了。 
