#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: history
#+hugo_categories: log
#+hugo_draft: false
#+description: 转眼又是一年
#+author: Dantezy
#+date: 2023-12-30
#+TITLE: 个人春秋2023
* 缘起
其实差不多每年都会写总结，散布在我的博客里面。前年写了一篇[[https://zhangyet.github.io/archivers/summary2021][《日月忽其不奄兮，春与秋其代序》]]，
开始把体例定下来，去年写了[[https://dantezy.xyz/posts/history-2022/][《个人春秋2022》]]，连题目都定下来了。

今年总体来说比较平淡。最重要的变化是在10月底做到了睡眠规律（其实挺了不起的，睡眠不好十多年了）。

写的时候除了日记之外，我的 telegram channel 也很重要，我更多地用 telegram channel 作为记录随感的工具。
* 2023
** 一月
我外祖母去世了。

从 [[https://t.me/danteslimbo/1347][telegram 的记录]][fn:1]来看12月全面放开带来的冲击已经平稳。我家人没有得新冠的，比较幸运。
** 二月
新加坡2月9日宣布全面解除抗议措施。2月13日开始公共交通不再需要戴口罩。这个政策对我影响比较大，因为我是那种能不戴口罩就不戴的人。
当然直到10月中旬，医疗机构依然要求病人佩戴口罩。

[[https://zh.wikipedia.org/wiki/2023%E5%B9%B4%E4%B8%AD%E5%9B%BD%E9%AB%98%E7%A9%BA%E6%B0%94%E7%90%83%E4%BA%8B%E4%BB%B6][中美气球事件]]。整件事件给我的感觉就是闹剧。美国政府行动的出发点不是「应该怎样处理」，而是「如何表演好」。
表演成了当代政治最重要的课题。
** 三月
美国科学家 Dias 宣布发现室温超导，后面还有韩国 LK99 事件。这件事在社交媒体上反应没有 LK99 事件那么轰动。
但实际上它更严重，因为 LK99 只是发了在 arxiv 上，但是 Dias 是发在《自然》杂志上。对这个事件的评论会放在 LK99 事件处。

中国、沙特和伊朗发表联合声明，沙特和伊朗将重启外交关系。

美国硅谷银行破产。后续没有太多连锁反应。

3月13日，和我的朋友 J 去看了《铃芽之旅》。其实我不怎么喜欢新海诚，以前在北京看《你的名字》还好，因为当时年轻，
而且是跟朋友一起看的，现在朋友歧路东西，年齿空长，实在可悲。不过我记这件事的原因是：付款给 J 的时候我把网银的 pin
输错导致我的网银被锁了。

3月22日，Indeed 新加坡裁员。本来以为这已经是2022年裁员潮的余波，后来发现，2023年也是那么糟糕。高台多悲风。

3月30日飞回广州，这是我来新加坡之后第一次回国。主要原因是防疫政策（隔离真是太要命了）和机票价格。这次买的酷航（新加坡廉航）
才100多新币，缺点就是我要在5点出发。
** 四月
4月首先在家度假，然后去深圳 *自费* 出差了两周[fn:2]。自费出差的主要原因是要去见我的新上司。在互联网行业工作这么久之后，
我反而认为人跟人之间就应该面对面交流。在线沟通，尤其是靠即使通讯软件沟通往往是不够的。

本来我想写一篇游记，记录一下这次回家的见闻，拖着拖着就不想写了。现在简单叙述如下：

1. 长途客运萎缩。因为没有高铁，所以一般我都会在广东省汽车客运站购票回家，这次购票的时候发现班次明显减少（以前往往半小时一班）。
   售票大厅的售票窗口也裁减了，换乘自动售票机器。后来我坐车从老家回广州，用来载客的汽车缩水了一圈。
2. 我老家开了不少幼儿园，还有一些养护机构，居然还有月子中心。我爸妈请亲戚过来吃饭，二胎还挺多的。我小学老师，他儿子都毕业工作了，
   居然也有了一对双胞胎女儿，太阳系之光。
3. 我父母终于搬到他们买的商品房里面。不过新家跟旧家都很潮，回南天回家不是一个好选择。
4. 我的猫阿 cat 在我去深圳的时候从家里跑出去了，但是后来奇迹般跑回来了。
5. 4月11日到深圳的时候，地铁还会要求戴口罩，后面4月20日就不再要求了。
6. 桃园地铁站，2019年我去深圳工作的时候在施工（当时是建地铁站），这次回去依然是工地（旁边的医院还在扩建）。
   跟朋友徒步完了，还是看到一片大工地。整个深圳给我的感觉就是一个巨大的工地。
7. 见了若干网友（感动），还抽空回去以前住的城中村看了一下（非常无聊），那里的主路终于修好了。
8. 在桃园旁边租的酒店里面放着振动棒和飞机杯，真是野啊宝贝，想起21年去上海，发现酒店有飞机杯和跳蛋。
** 五月
5月5日，WHO 宣布新冠疫情不再构成国际突发公共卫生事件。至此，我没有在疫情期间检测阳性过
（实际到写作的时候<2023-12-28 Thu 10:16>都没有）。

5月12日，《塞尔达传说 王国之泪》发售，这是今年我花费时间最多的游戏。沉迷这款游戏让我又重新开始熬夜，睡眠再次紊乱。

5月13日，笑果脱口秀演员 house 在演出中使用「能打胜仗，作风优良」比喻他看到的野狗。

5月15日，著名程序员陈皓猝死。要多关注心脑血管健康啊。

5月28日，C919 首飞（商业飞行）。
** 六月
新加坡裔脱口秀演员 [[https://www.zaobao.com.sg/realtime/world/story20230613-1403803][Jocelyn Chia 事件]]发酵。这件事可以跟上个月 house 的事件发生了。

第一次张雪峰争议言论事件（新闻学劝退）。

6月23日，瓦格纳兵变。
** 七月
7月9日，通关《王国之泪》。

7月13日，吐缇在 B 站发视频说下个月有巡演。笑果挨了铁拳之后，旗下艺人基本偃旗息鼓。我不确认这个时候吐缇是否还是笑果员工。

7月17日，在服务器上部署了一个 matrix 实例，不过作用不大。因为身边很少人用 matrix 。

7月26日，LK99 预印本发布。这一天舆论不是很热。到7月29日讨论的热度就很高了。

7月29日，重新在 Duolingo 学习日语。
** 八月
8月18日，卓里奇去世。很惭愧，两方面，一方面是我以为他老人家早就过世了，另一方面是他的分析教材我从来没有读完。

8月22日，买的摩卡壶到了。更早之前我买了手磨，订阅了咖啡豆，开始手冲咖啡。

8月23日，印度探月成功。

8月25日，普里戈津飞机失事，死亡。我在想我们看普里戈津会不会像当年苏联人看林彪（应该没有，普里戈津没有林彪的地位和权势）。
** 九月
9月1日，新加坡总统选举，可以多放一天假。这样新加坡的公众假期在数学期望上略大于11天。

9月9日，李佳琦直播事件（79元眉笔事件）。

9月25日，失眠，跟着张朝阳的书从狭义相对性原理出发，推导洛仑兹变换。

9月17日，开始看 MyGo，要一辈子哦！

9月29日，许家印被捕。
** 十月
10月7日，哈马斯进攻以色列。

10月10日，买了一个 pixel 手机，拿快递的时候，脚滑了一下，导致我痛风复发了，我还以为是骨折了。

10月一连串睡眠记录良好，我认为我的睡眠已经达到一种稳定状态。
** 十一月
11月18日，OpenAI 公司高层闹剧，这场大戏在11月23日就结束了，Altman 回到了他忠诚了 OpenAI。

11月24日，去看了一场歌剧，认识了新加坡网友严老师。

中美元首会面，具体日期懒得翻了。
** 十二月
回国一趟消化年假，参加我发小的婚礼。顺道去了上海见了一些许久不见的朋友。

12月22日，版署忽然出了一个草案，出台更严格的游戏管控政策。
* Footnotes

[fn:2] 不如 ENJOY。 

[fn:1] 这条记录是我观察朋友圈的结论，可靠性一般。 
