#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: history
#+hugo_categories: log
#+hugo_draft: false
#+description: 2025年也过去了，没有打世界大战，可喜可贺，可喜可贺。
#+author: Dantezy
#+date: 2025-12-31
#+TITLE: 个人春秋2025
* 日记与遗忘
2019年开始用带格式的文本文档写日记，存在 git repo 里面。从2021年开始每年会写一篇总结。
到现在也算是养成个好习惯了。

前不久跟朋友说起这个习惯，伊问我写日记是不是就像清空了大脑的缓存？

其实不是，日记与记忆的关系非常复杂。在写这篇总结之前我重新翻了一下今年的日记，
凌乱琐屑。有很多事情我没有写下——而且是刻意没有写下，但翻到与之相关的日记时还是涌现了，
有些当时写下的日记，现在我已经忘记当时到底发生了什么。而且现在我随手在 telegram channel 留下的记录更多，
我就放佛《迷雾之子》里面的藏金术士那样将记忆藏在赛博空间里面。

日记以及其他记录没有写下的内容就像光谱分析里面的被吸收的谱线，无反映着存在。所谓修辞立其诚，
我保证写下的内容都是真实可信的，但我会通过裁剪写下的内容使叙事偏向我自己。
某种意义上回顾就是回想这部分裁剪，然后继续裁剪——而写这篇总结，本身就是进一步裁剪之前的记录。

今年沿用去年的体例，用一些问题组织本文。
* 今年花得最值的一笔钱
毫无疑问，是花在望远镜的钱。我买了两个望远镜，一个是天虎旗云10X42 APO 望远镜，另一个是胜途 Lambda 8X25
ED 望远镜，我12月18日查了一下，胜途这望远镜我双十一买的时候是798元，已经涨价到950元了，
虽然天虎旗云那款从2480降价到2380，但是算下来还是有赚，这是一个小惊喜。

这两副望远镜对我最大的意义就是开启了我的观鸟之旅，今年写了三篇观鸟相关的博客：

1. [[https://dantezy.xyz/posts/birding-20251011/][《观鸟记: Tampines Eco Green 20251011》]]
2. [[https://dantezy.xyz/posts/birding-20251101/][《观鸟记：Sungei Buloh 20251101》]]
3. [[https://dantezy.xyz/posts/birding-20251222/][《观鸟记：20251214, 20251220, 20251221, 20251225》]]

观鸟给我带来了两个改变：

1. 因为观鸟需要早起，我在12月睡眠改善了不少，睡眠事件从平均6小时左右上升到6小时45分左右，
早上也能在8点左右起床。

2. 开始观鸟之后，去到不同的地方都开始留意附近有没有鸟，从观鸟开始我也开始留意植物和昆虫，
可以说，整个世界都变得更细致了。

* 今年做过最有意义的一件事
我做了一个播客：[[https://www.xiaoyuzhoufm.com/podcast/68a0c83b0a34ca06a967a96d][《开卷八分半以内》]]，在这个播客的第14期，我解释了这个播客的缘起和部分改变。

这个播客的意义在于：它起码是一个创作，为了维持周更，我每周会产出一篇两千字左右的书评，
播客是一种表达，要表达就要思考，就会从一个播客创作去审视一本书。

当然这个播客目前做得一般（悄悄说一句，我自己都不听的）。但我会做下去，我朋友的岳父神蛊温皇说过：
死去的高手就不会再进步了[fn:1]，而继续做就有进化的可能。
* 今年最推荐的文化产品
嗯，想了一下，很难推荐，音乐向来不是我所长，直接跳过。电影今年兴趣也不大，除了《链锯人：蕾塞篇》，
甚至连印象深刻的片子都没有。

游戏方面我正在玩《博德之门3》，这款游戏还需要推荐么？除此之外，我一度沉迷《逃离鸭科夫》。
但我最终决定推荐《都市传说解体中心》，虽然这是视觉小说，游戏性一般，但是我就喜欢它那种神神叨叨的劲头。

我很用力地读了[[https://book.douban.com/subject/37194302/][《对工作说不》]]，并且为这本书做了三期播客，
但正如我在节目里面所说，这本书对现实描述有力对缺陷一针见血，然而提出的解决方案非常无力。

写这篇总结的时候我还没有读完[[https://book.douban.com/subject/36424128/][《矩阵力量》]]，这本书 A. 很有用；B. 有缺陷。你要说「虽然 A 但是 B」也可，
说「虽然 B 但是 A」也可以。

思前想后，我决定推一个书单：[[https://weread.qq.com/misc/booklist/10900029_80yZVORiF][厄休拉勒古恩——以想象创造世界]]。这是一个微信阅读上的书单，我今年读了很多厄休拉·勒古恩的书。
读完伊的访谈录《以想象创造世界》之后整理了这个书单。
* 明年的愿望与计划
翻了一下去年的计划：

1. 观鸟，实现了，今年看到72种鸟，部分记录见前面。
2. 去日本旅游，也去了，虽然每次都有点波折，见[[https://dantezy.xyz/posts/tokyo-202507/][《东京也无非是这样》]]还有我一直还没写完的京都游记[fn:2]。

两个计划都完成，想不到，其实我半途而废的事情挺多的，今年本来想写漫评的，结果一月拖到二月，二月拖到三月，月更拖成季更，
最后更了一季就太监了：[[https://dantezy.xyz/posts/manga-2025q1/][《2025年Q1 漫画月旦》]]。

明年的计划是：

1. 给开源社区贡献五个PR（大概率还是 bpftrace ）。
2. 组织两次以观鸟为核心的旅行。
3. 去莫斯科旅游（可选）。
* 代表今年的诗
想不到写这篇总结最难的部分是选一首合适的诗词[fn:3]。

今年开始读辛弃疾的全集，但是没有一首词适合放在年末，有些送别感怀的诗又显得太伤感了。所以今年留空。
* Footnotes

[fn:3] 当然忍住罗嗦吐槽的欲望也不容易。 忍不住的话写到明年都写不完。

[fn:2] 写播客稿跟观鸟确实挤占了时间。

[fn:1] 这是《金光布袋戏》的梗。
