#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: history
#+hugo_categories: log
#+hugo_draft: true
#+description: 2022年年度总结，起名春秋，不是「知我罪我，其惟春秋」，而是「春秋断烂朝服」的意思，另外也有「春秋笔法」的意思。
#+author: Dantezy
#+date: 2022-12-28
#+TITLE: 个人春秋2022
* 缘起
去年在河边散步起意背《离骚》，半途而废。倒是有意模仿春秋，写了一篇[[https://zhangyet.github.io/archivers/summary2021][《日月忽其不奄兮，春与秋其代序》]]，这是一篇总结性的文字，
从我过去一年的日记，筛选每个月的大事（更主要是我的大事），回顾与反思。今年也写了不少日记，我决定也写一篇类似的文章。
起名春秋，不是「知我罪我，其惟春秋」，而是「春秋断烂朝服」的意思，另外也有「春秋笔法」的意思——有些我不明说的东西，
大家可以从我的遣词造句中看出我的态度。

我有意把我的日记作为一种史料，尽管价值不大[fn:1]。单纯的记录其实没有什么意思，但是以自己的日记为经纬，反思回顾一下过去，
对我本人还是有点意义的。

* 2022
** 一月
舆论最轰动的事件是丰县铁链女事件，这件事我有些看法跟我的朋友阿北说过。

冬奥本身是一件大事，但我不怎么关心，日记里面都没有提。

1月10日，开始会办公室上班。
** 二月
2月24日[fn:2]，俄罗斯跟乌克兰开战。这件事基本就是2022年世界影响最大的事情。知道战事开始的时候，我正在做 KVM 的 IO 测试，
测试结果显示随机 I/O 比顺序 I/O 快得多，这并不是一个合理的结果，我对此非常焦虑。如果不能完成这个测试，我不好意思第二天请假玩游戏。
俄军并没有快速取得胜利，令我忧虑核战的风险。

2月27日，去了女皇镇卫理公会，开始新加坡基督教会活动。
** 三月
3月13日，去了 LDS 在 Newton 的教会，关于 LDS，我在《[[https://dantezy.xyz/posts/singapore-lds/][新加坡观察：基督教后期圣徒教会(LDS)]]》一文写过[fn:3]。

3月18日，买了个服务器，准备从头搭建个人博客。见《[[https://dantezy.xyz/posts/yesterday-once-more/][博客迁移日记]]》。

3月22日，我室友感染新冠。当时公司还执行申请 WFO 制度：每周申请下周要不要来公司上班，申报的时候要说明疫苗接种情况、是否去过高风险地区（国外、医院）和
是否有跟新冠病人接触过。我嫌麻烦没有申请但是天天跑来公司上班，当天为了参加同事组织的活动被 People Team 抓个正着。下班的时候收到室友的信息，吓了一跳。
最后我居家办公了一周，也没有感染。

3月27日上海市实行分区分批封控，但其实这件事我没有在日记里面记录，我是想起有个叫《四月之声》的视频才想起上海三月封城，然后从 wikipedia 查回来。
上海封城是中国防疫的一个重大转折。在写这篇文章的时刻（2022年12月28日）回顾当时的决策，我觉得错过了一个放开的好节点，很有可能上海3月的时候，
感染已经无法通过清零控制了，但是基于政治原因（10月的二十大），后续依然选择成本大收效小的清零政策（主要是常态化核酸和密接隔离）。

3月28日东航坠机，到本文写作时，还没有正式报告。

京东这个月发生了毁三方事件，31日还有马来的同事问我，三方是什么东西，见[[https://t.me/danteslimbo/489][这条吐槽]][fn:4]。当时觉得京东挺不要脸，现在想来，更不要脸的公司有的是。
** 四月
4月4日，第一次跟我们组的越南小伙见面（不过写这篇博客的时候他转组了）。

4月8日，去 CMGS 家聚会，醉酒，回来宿醉，然后戒酒，这次戒酒成功了，见《[[https://dantezy.xyz/posts/sobriety/][戒酒记]]》。

4月28日，《四月之声》事件。所以说人的记忆就是不可靠，不查我还记得《四月之声》是4月1日晚在朋友圈大规模流传的。
** 五月
5月15日，天问一号登录火星。

LDS 的传教士本来兴冲冲地跟我规划了5月28日受洗的计划，但我还是坚定地在5月24日拒绝了，和两个传教士在新加坡河边愉快地侃了一阵，我终于问了他们关于进化论的看法了。
** 六月
6月1日，上海解封。

6月2日，亚马逊宣布 kindle 一年后退出中国（一月份有一条 kindle 缺货的新闻跟这件事有关联）。我连夜把所有的 kindle 电子书都搞下来 DeDRM 了。当然，搞下来的书我基本不看。

6月3日3点-9点之间，微信开始近几年开始的「技术维护」（当然大家都知道这是因为六四事件），禁止用户更新头像，今年的技术维护一直持续到6月6日。
李佳琦直播间出现坦克（其实是轮式战车）造型蛋糕被封禁。

6月10日，唐山打人事件，这件事我其实没有写在日记里面，还是后面写福建舰下水的时候才回想起来。

6月14日，得知黄文择去世，虽然我已经不看霹雳了，还是觉得有点伤感。比今年其他去世的名人都要伤感。黄泉之下，九音才子再续未完传奇。
公司第一轮裁员。

6月17日，福建舰下水。电磁弹射平直甲板，挺牛逼的。

6月25日，我祖母去世。当天我重感冒，在床上昏睡到半夜收到我父亲的信息。

6月27日，北京党代会发言的时候提到「五年内会坚持常规化防疫」，新闻稿出来之后又把这个表述删除了。有些朋友说这意味着防疫常态化要无限期延续。
我在日记里面说「我不觉得这种态势会继续，因为钱不够，而且防疫的政治风险也很高。保不齐有人憋着自杀一把就是很严重的舆情事故。」想不到居然被我说中了。

6月30日，行程码取消加星。
** 七月 刺激的月份
7月3日，倪匡去世，我在日记还记成倪震去世了，看来我是太爱周慧敏了。

7月4日，上海泄露了一份巨大的个人信息。因为实名制，所以隐私被泄露，因为隐私被泄露，所以需要实名制去防诈骗，劳而无功的维稳政策。

7月7日，得知高桥和希去世（10月14日，日本海上保安厅也正式宣布死因，高桥和希是在冲绳拯救溺水者而死的）。当时不觉得悲伤，起码不觉得比三浦建太郎死讯更伤心。
鲍里斯辞职。

7月8日，安倍晋三被刺杀。又不是二二六和除虫射日[fn:5]，没什么好说的。

7月10日，河南银行事件，储户跟警方发生冲突（之前的赋红码事件也放这里吧）。这个事件我觉得很严重，因为有暴雷消息的银行不少，而且在这之前还有公务员发不出薪水的传闻。
我近年的观点是财政才是政治最基础的问题，没有钱，不是问题也变成问题，有钱，绝大部分政治问题都能解决。事件最后被平息——当局垫付了储户的钱。

7月13日，得知我初中的班主任因病在出租屋去世。当天我难受了一天。我最后一次跟他交流是在一个师妹的 QQ 空间，他说这个师妹太理想主义，我说你怎能这样泼别人冷水。然后吵了一架。
认识这么多年，有过开心的时刻，有过龃龉。现在回想起来百感交集。

7月22日，我的微博被封了，直接原因是我说「滴滴因为数据问题被封，那之前上海数据泄漏，多少得杀几个官员祭天吧」（大意）。当然我觉得也不一定就是这条微博被封。
发了微博管理员不喜欢的微博，该微博的阅读数往往就是0，或者停在某个数值不增长。我猜测如果命中模型那就直接是0。被封杀的微博阅读量不会变，而且不能被转发，作者自己可以看见。
我被封禁的微博虽然不多，但也有十几条。所以我怀疑用户封禁是算分，达到一定阈值再封禁。

7月25日，我妹把阿 cat 接回老家了。
** 八月
8月3日，佩洛西访台。下午上班的时候我们围观了飞机的实时轨迹。最后她平安落地。民族主义比较强的网友气愤不已。我觉得没有打起来真是太好了。
单纯从公关角度来看，我觉得中国政府公关水平不行。我要是入主中南海，7月底我就去订购一批烟花，实在阻不了佩洛西降落的话，我在就金门放烟花：欢迎佩洛西女士来华访问。

8月6日，申诉之后微博解封了。

8月9日，一篇比较出圈的[[https://www.pingwest.com/a/268448][品玩文章]]发布。不少朋友就这篇文章的内容过来问我，我也觉得是一个乐子。不过我关于这篇文章的预测后续被证伪（可见我的预测能力是多么差）。

8月25日，著名的[[https://zhuanlan.zhihu.com/p/559299936][「人在新加坡刚下飞机」]]事件。

8月31日，戈尔巴乔夫去世。公司以割包皮的气势裁了若干团队。
** 九月
9月9日，伊丽莎白二世去世。

9月15日，公司发了邮件说要缩减开支。

9月16日，进行了可见的将来最后一次团建（这是合规的，因为这次团建是在15日邮件之前获批的）。

9月19日，大裁员。第二天平时跟我们一起吃午饭的某团队的两个朋友被裁了。裁员这种事，亲身经历才知道压力大，一方面担忧裁到自己头上，裁到关系好的同事头上也很悲伤。
* 总结
* Footnotes

[fn:5] 话说回来，朴正熙死了也是便宜全小将而已，该怎样还是怎样。
 
[fn:4] 四月还有另外一条[[https://t.me/danteslimbo/495][吐槽]]。 

[fn:3] 其实我还打算谢谢卫理公会的，但是一直拖着没有写。
 
[fn:2] 美国一直说2月16日会开始，但2月16日没有开战，最后在24日开战，中间到底发生什么就留待历史学家考证了。

[fn:1] 见 https://t.me/danteslimbo/543 
