#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: history
#+hugo_categories: log
#+hugo_draft: false
#+description: 中学母校25周年了，回忆一下那里的生活。也回答一个我自己的问题：如何度过不快乐的人生。
#+author: Dantezy
#+date: 2025-04-18
#+TITLE: 回忆我的中学母校
#+SUBTITLE: 如何度过不快乐的人生

我中学的母校4月19日25周年纪念，我也不知道为什么是4月19日，而不是秋季学期开始的9月1日，
不过算了，留给后世的历史学家吧。
* 六年中学——住宿
我的母校也叫实验中学[fn:1]，所以下文简称实中。我们那个小县城有三所「重点中学」，
但它当时是最次的那间。为什么我去那里呢？因为那些年改革，其余两所重点中学不招初中，
所以我没得选。

实中本来在旧城区，跟当时的师范学院靠近，也跟我五六年级的小学比邻。不太清楚什么时候搬到了新校舍。
新校舍在大路边，教学楼分两翼，每翼三排教室，中间是两个行政楼，总共8个楼围出中间的广场，
广场上有个舞台，旗杆就在舞台旁边，每周的升旗仪式在这个广场举行。元旦晚会和集体看电影[fn:2]也在这里。

在整个六年里面，实中都没有足够的宿舍容纳所有的学生，只能提供给住宿的女生和毕业生（初三高三）。
初中的时候我们就住在教学楼的四楼，高一高二换到中间的空置房间。
寝室其实就是空置的教室，一间本来容纳60人的教室，放满上下铺的床，睡一堆学生（大约40人），
冬冷夏热[fn:3]。风扇无法覆盖所有的床铺（有些上铺都吹不到，更遑论下铺）。

我们每天起床需要叠被，而且很奇葩的是如果挂了蚊帐，早上需要叠起来。我后来干脆不挂蚊帐了，
一方面是怕麻烦，另一方面是热——居然没有因为蚊虫得病，我很幸运。住宿的人还要轮流打扫卫生，
把地面扫干净，还要拖地。我讨厌这种清洁工作。床铺上一般是劣质的草席，会不断掉草屑到地上，
很难打扫干净。

学校提供了男女澡堂，但我几乎没有去过，男澡堂里面没有隔间，我都忘记里面有没有热水供应了。
为了节省时间，我们都是在教学楼的厕所里面解决洗澡问题。这破教学楼水压不行，
傍晚下课之后三四楼基本没有水，我们只能用水桶在中午等一桶水，晾到晚上，用一桶水洗澡
（我不记得当时是不是还要靠这桶水把衣服也洗了）——这还得指望同学素质在线，不偷水。
厕所里面隔间的门经常是坏的——我过年回去看了一下，坏更多了，有些我怀疑是从我读书的时候坏到今年。
隔间门也就算了，因为水压问题，这些厕所隔间也不一定冲得干净，下水道堵了也得等很久才能被处理，
里面有什么我就不说了。

晾衣服也令人头痛。衣服只能自己手洗（不知道现在会不会有洗衣房），拧不干，晾衣服的地方不够，
衣服挤在一块，有时候只能穿没干的衣服。所以广东特产回南天就是我当时的一大噩梦，衣服干不了，
地板湿淋淋——尤其是轮到我搞卫生的时候——记忆中我总会在回南天轮班搞卫生（但也没啥稀奇的，
回南天这么长）。无关因果，我必须说： *我讨厌搞卫生。*

初三高三住到正式的十二人间宿舍，条件也就那样了，供水、潮湿、风扇一个都没解决。
男女生宿舍是一个建筑，采光很糟糕，男生住一二楼，有两道门隔开男女宿舍——这么多年没发生火灾，
幸运。晚上从教学楼回去宿舍这一路，倒是有点意思，但也没有发生过什么深刻的记忆。

当时中午强制午休，我不怎么睡得着，睡醒之后经常会惆怅，茫然若失。
教学楼旁边有个塔楼，是上下的楼梯，我记得有个午后，我从这个塔楼跟教学楼之间的空隙，
看到一片灿烂的蓝天，这一瞥的印象反而是我后来时常回忆起的一刻。
* 六年中学——教学
从我上中学开始，应该就是早上7点开始早读，但是会要求6:45（还是6:50）到教室，提前开始早读。
7:30 下楼做早操，忘记什么时候开始第一节课了，每节课是40还是45分钟我也不记得了。
晚自习也是晚上7点开始（同样要求提前一点到），不住校的学生晚上9:40回家，住校的学生继续到10:10（
还是10:20，我记不清了）。

而且从初中开始，我们就会在周六上课，高二和高三最后的模式是每周上六天课，周日再自习半天，
初中有没有到这个程度我就不记得了。

初中的班主任是英语老师，他这个人有点流氓气，但是很多学生都会喜欢他。
我还记得和其他学生去他的宿舍作客[fn:4]。我们周六的补课，他给我们讲《新概念英语》。
当时的生物老师，给我们上课的时候，问：「为什么邓小平抽烟喝酒，活到九十多？」，
我们当时猜了个边，只有一个同学说：「他是例外的」。老师说对。
我一直都记着这个故事，每次面对网络热点的时候我都想这个例子，
想着网络上唾沫横飞的分析背后到底有没有数据支持（绝大多数都没有），
他们到底是一个现象？还是单纯一个例外点。

其实我初中的时候一直都不觉得自己学习成绩好，现在回头看，实在有点杞人忧天了。
因为回头看我的成绩排名，和重点高中的招生计划，我完全不需要担心的。

初中三年都在同一个班同一个教室过了，高中有点不同，因为高二有文理分科。
我都记不得高一的教室在哪边了，好像还在原来初中那一侧，
我有一个跟同班同学以及他隔壁班的女朋友一块吃饭的记忆，是在原来初中那一侧。
但另外有个在数学课上看《安娜·卡列宁娜》的记忆是在另一侧。

不过这都不重要，我高一的班主任是我唯一觉得「糟糕」的教师，在我们这个没啥教育资源的地方，
其他老师最多也就平庸，唯有他，我没有从他那里学到任何东西。
高一的时候我就自顾自把练习册做完了。对我来说，他唯一的优点就是不管我。

后来文理分班之后，高中的生活就变成预备高考，高二把课程上完之后，高三基本都在备考。
那时候每个月都会有月考，月考还会有排名。我高三的数学老师也挺厉害的，讲课很好[fn:5]。
他教了我一个原则，「我说过的话，如果没有录音，出了这个门口我就不认。」
* 六年中学——青春回忆
正如最好吃的北京烤鸭在郭德纲的相声里，最好看的樱花在动画里面，
我觉得美好的青春都在文艺作品里面。正如前面所说，偶尔的一片蓝天就是我的灿烂回忆了，
实际上我大部分回忆都是灰白的——就像我家冬天那灰白的天空一样。

现在忽然要回忆，我想到的都是一些片段。

初中去宿舍的第一天认识了 L ，他后来成为了我的同桌，初中三年里面最好的朋友。

坐我后面的女生[fn:6]借我哈利波特的小说以及动漫杂志——这动漫杂志的名字我忘记了，
大概是《动漫XX》或者《XX动漫》，我从这本杂志里面看到一张穿驾驶服的凌波丽，当时惊为天人。
后来跟班上另外一个同学借了 EVA 的盗版碟。

班上有个男生给我起了外号，这个外号怪讨厌的，但是我没啥反制的手段。
我忘记什么时候开始不再在意这个外号。我也不是什么完美受害者，我也给别人起过外号。

学校的饭堂难吃[fn:7]，伙食不断劣化（比如里面的煮牛肉，最开始是纯牛肉，后来往里面掺了萝卜），
而且去晚了，基本是残羹剩饭级别了。我们都痛恨上午最后一节课拖堂（延迟下课）。
下课铃一响我们就不顾安危地冲出去，冲到饭堂打饭。我记得有一次在走廊上，
我要闪避前面的人，作了一个横向机动，被我同学撞到仆街。按交规是我全责，我同学也很仗义，
帮我打了饭[fn:8]。

说到饭堂，我们当年有个饭卡，定期往里面充钱。我是没有零花钱的，家里每个月100块充饭卡。
我就从饭卡里面省了点钱出来买课外书。为了省这些钱，我每顿饭就把蔬菜省下来，
也尝试过老干妈拌饭，腐乳拌饭等不太健康的生活方式。

学生饭堂最初是一个铁皮顶的平房，没有坐的位置，只有卖饭的窗口，我们去打完饭带回教室吃。
里面非常拥挤，我当时经常干的缺德事就是插队。最迟在初二的时候，我开始帮别人打饭，
收一些报酬：或者是对方用饭卡请我吃饭，或者是给我一点的现金。

为什么初二我记得那么清楚呢？因为那年我一个小学同学溺水死了。上一周我还帮他打饭，
第二周回来，他的同班同学，也是我在小学认识的一个熟人找到我，说：
「你知道，XXX 死了。」我还记得不久之后——可能就是当天晚上，我梦见了这个溺死的同学，
他跟我说，那谁骗你的。

说到买书，我们那个小县城，没啥严肃的书店，基本都是靠卖教辅存活的。但是初中的时候，
邮购买书开始，我知道的第一个提供邮购方式的是贝塔斯曼书友会，不过这玩意太贵了。
很快被九久读书人取代了。最初的方式它邮寄购书目录，具体怎么下单我忘记了，
可能九久已经是在网上下订单。不过很快，九久又被当当跟卓越取代了，
这个我就可以肯定是在网上下订单，我应该还有163邮箱注册的帐号。当时没有支付宝
（我银行卡都是读大学时候才办的），只能去邮局汇款。到高中我拓展了一点生意，
帮其他同学买书，然后通过我的会员权益和优惠券套利[fn:9]。

高中还跟其他同学从批发市场买来零食带到班里卖，这个生意不是我初创的，我中途加入。
赚了一点，后来也不了了之，这个生意最后的孑遗是我的 QQ 邮箱名。

回忆在此打住就好了，不然可以写到明天。
* 如何过好一个不快乐的人生
我听《无聊斋》，刘旸教主就说，浙大入学会找写杰出校友过来演讲，
但为什么没有人来教怎么过一个不杰出的人生呢？

同样道理，这个世界上也没有人会教人「怎样去过一个不快乐的人生」。

我现在可以大大方方说了：「我过得不开心。」我甚至可以说我都找不到让我过得开心的方法。
如果我处于正面情绪的时候记一个正数，处于负面情绪的时候记一个负数，
我觉得从我记事开始，任何一段足够长时间内做积分，最后得到的值都是负数。
按这个定义来说，我是可以天天 cos 若叶睦说：「我从来没有觉得 XXX 开心过。」
XXX 可以替换为任意足够长的时间段。

我现在想法就是「不开心就不开心吧，难道我还死去吗（郭德纲）」。
套用《炎拳》的说法就是：即使我们要承受所有的痛苦，那也绝不能接受死亡。

因为不高兴就是情绪，情绪是实在的，任何事情都可能在我心中掀起情绪的波澜。我现在想明白的事情是，
虽然情绪真实不虚，但是情绪变幻莫测，大概就是《金刚经》说「一切有为法，如梦幻泡影」的意思。
我明白这种变幻，但我不可能四大皆空（所以我没法成佛）。

这么多年靠互联网混饭吃之后，我有点幻灭地发现，互联网现在基本变成一个情绪放大器，它不再是我梦想里面那个弭平信息差距的神器。
幸好我也不是那种理想一破灭就去死的理想主义圣徒。现在的互联网把个人的情绪放到非常重要的地位，这走了一个极端，
这个极端跟我有点相反，我过去一直很压抑情绪的表达。两种极端都不太好，不能把情绪放到最重要的地步，也不能忽视，
我现在开始正视自己的不高兴，但也不会说因为自己不高兴就像世界都欠了我钱一样。无论佛家讲中道，还是儒家讲中庸，
都不会让我们走极端，所谓「人心惟危，道心惟微，惟精惟一，允执厥中」。日子还很长，所有激烈的情绪都会随风而去，
The answer my friend, is blowin' in the wind, the answer is blowin' in the wind.

* Footnotes

[fn:9] 我是怎么从一个靠信息差套利的精明小气鬼变成现在这样 coupon 都懒得用懒得算的的懒人的呀？

[fn:8] 这么多年也没有什么大事故，还是幸运。 

[fn:7] 我怀疑我能忍受新加坡食阁，主要因为这六年的锻炼。但说句公道话啊，
实中饭堂味道虽然不咋的，但是好歹是热的，比新加坡那些凉掉的菜饭好一点。

[fn:6] 后来我毕业的时候甚至还向她借过钱。 

[fn:5] 但我高考数学成绩不好，觉得怪不好意思的。

[fn:4] 当然后来我跟他闹翻了。 

[fn:3] 这些教室本来是安装空调设计的，但知道我毕业都没有装上。

[fn:2] 但除了一部《非典人生》，我不记得在这个广场上看过什么电影了，本地现代一点的电影院要到高中才开，
我在里面看了《通缉令》。

[fn:1] 当然跟广东省实验中学不可同日而语。 
