#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: ipoh travelling
#+hugo_categories: log
#+hugo_draft: false
#+description: 记录一下 Ipoh 旅游的经历。
#+author: Dantezy
#+date: 2024-04-23
#+TITLE: 怡保游记
* 缘起
我不喜欢旅游（虽然也不讨厌），但是问我想去哪里旅游，我基本没有没有想法。
我倒是可以说，我怕麻烦，而且抠，所以需要签证机票贵的地方基本绝缘。
但这不是根本原因，即使有任意门，我也没有什么特别想去的地方——这可能是精神阳痿的一种。

之所以会去怡保旅行，因缘起于2月新加坡航展上认识了小柯，他在那附近上学，向我推荐了一番。
种子种下了。后来3月团建的时候我得知隔壁组 PM 是怡保出身了，种子发芽，长成大树。
买票、请假、定酒店一气呵成，就这样去了怡保。
* 旅途
这次买了 AirAsia 的机票，从樟宜机场4号航站楼出发。4号航站楼仿佛是樟宜机场飞地，Google Map
还不提供「从别的航站楼坐摆渡车过去」路线的时间估算，出发的时候只好地铁转公交（我最讨厌公交）。

从樟宜到怡保的航程不长，一个多小时就到了。但是途中有点小颠簸，让我有点怀疑人生，要是机型是波音的话，
我估计得临时信一下上帝。

怡保机场不大，我不知道它会不会佛山机场大（主要因为我没有做过佛山机场的航线）。过海关的时候排队非常慢。
我本来排在外国人的队伍，大马人都排完了还没轮到我，于是旁边的警官让我过去大马人的窗口。
出发的时候我看了外交部网站，把 MDAC 打印出来了，结果没人看。后来问了一下，填了信息可以查到，但是不填会要求现场填。
估计就是有人没有填。
* 进城
从机场出来打车去吃了午饭，然后涂了防晒，准备走路去酒店。

来之前我的朋友小柯跟我说，别走路，打 Grab，体感温度40度以上。

但我还是选择了走路，主要原因是：

1. 买了防晒，这钱不能白花。
2. 酒店是三点入住，吃完午饭才一点多，可以浪。
3. 我想看看本地。

从饭店去酒店就是一个从郊区到市区的过程，特征很明显。Ipoh 其实挺像我家乡的，到处是山。
在路边房子后面一两百米就是群山。

前半段路很少商店，路过一个公园，我才在一个餐厅买了一杯可乐。进入市区又在7-11买了瓶装水。
郊区和城区的分界还是挺明显的。路上很多标志牌只有马来文，也有华文的（但是我没留意华文标志牌有没有马来文）。
但是很少英文。

路过 Sekolah Raja Perempuan Taayah  一所马来人女校的时候正好是课间休息，带着头巾的小姑娘们在走廊上。
她们看到了我，还有点雀跃，我向她们挥了挥手，有一群留意到我的学生也挥手回应了。当时我正好在听《无聊斋》，
有个在光线传媒工作的嘉宾聊到黄百鸣，所以这个场景让我想到《开心鬼》。

入住之后发现我整件T恤乃至裤头都湿透了，靠了一下枕头，连枕头都变潮了。睡一觉，然后起来吃晚饭。
* 饮食
第一顿是从机场出来的[[https://maps.app.goo.gl/ELfece8oCyLZ628T6][烧腊]]，里面的烧鸭是烟熏风味的，烧肉倒是没啥，配的酱料就是这边麦当劳常用的酸甜酱，我不喜欢。

晚饭吃了[[https://maps.app.goo.gl/KMyWVxoQbfP1XxGQA][德记炒粉]]，这个店在新加坡好像有分店，我点了他们招牌的月亮河和文冬芽菜。

所谓月亮河就是咸鲜口的湿炒河粉，中间窝了一个生鸡蛋。文冬芽菜就是豆芽。我常见的豆芽是细长的，但这边的文冬芽菜是粗短的。
汆烫之后，淋酱油（可能是店家自己调整过的酱油），上面洒葱花和胡椒粉。

第二天早餐就在酒店附近找了个早餐铺，这个早餐铺有点像新加坡的食阁，好几家档口开在一起，顾客随便坐，
到档口点餐或者等人过来招揽生意，饭菜做好了送上来。早餐吃了咖喱叉烧粉。

上午逛了几个景点，午饭没有正经吃，吃了碗豆花，还吃了一种忘记名字的马来小吃，服务员是个包着头巾说粤语的阿姨，
估计是嫁给马来人的华人。

晚上回来终于吃到[[https://book.douban.com/subject/25727391/][《马来西亚：爱上迷路》]]里面提到的芽菜鸡（其实就是芽菜和白切鸡）。芽菜前文已述，
白切鸡就令人感动：假如你在新加坡活得足够久，那么你对白切鸡的要求会下降到「没腥味就行」。
