#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: ipoh travelling
#+hugo_categories: log
#+hugo_draft: false
#+description: 记录一下 Ipoh 旅游的经历。
#+author: Dantezy
#+date: 2024-04-23
#+TITLE: 怡保游记
* 缘起
我不喜欢旅游（虽然也不讨厌），但是问我想去哪里旅游，我基本没有没有想法。
我倒是可以说，我怕麻烦，而且抠，所以需要签证机票贵的地方基本绝缘。
但这不是根本原因，即使有任意门，我也没有什么特别想去的地方——这可能是精神阳痿的一种。

之所以会去怡保旅行，因缘起于2月新加坡航展上认识了小柯，他在那附近上学，向我推荐了一番。
种子种下了。后来3月团建的时候我得知隔壁组 PM 是怡保出身了，种子发芽，长成大树。
买票、请假、定酒店一气呵成，就这样去了怡保。
* 旅途
这次买了 AirAsia 的机票，从樟宜机场4号航站楼出发。4号航站楼仿佛是樟宜机场飞地，Google Map
还不提供「从别的航站楼坐摆渡车过去」路线的时间估算，出发的时候只好地铁转公交（我最讨厌公交）。

从樟宜到怡保的航程不长，一个多小时就到了。但是途中有点小颠簸，让我有点怀疑人生，要是机型是波音的话，
我估计得临时信一下上帝。

怡保机场不大，我不知道它会不会佛山机场大（主要因为我没有做过佛山机场的航线）。过海关的时候排队非常慢。
我本来排在外国人的队伍，大马人都排完了还没轮到我，于是旁边的警官让我过去大马人的窗口。
出发的时候我看了外交部网站，把 MDAC 打印出来了，结果没人看。后来问了一下，填了信息可以查到，但是不填会要求现场填。
估计就是有人没有填。
* 进城
从机场出来打车去吃了午饭，然后涂了防晒，准备走路去酒店。

来之前我的朋友小柯跟我说，别走路，打 Grab，体感温度40度以上。

但我还是选择了走路，主要原因是：

1. 买了防晒，这钱不能白花。
2. 酒店是三点入住，吃完午饭才一点多，可以浪。
3. 我想看看本地。

从饭店去酒店就是一个从郊区到市区的过程，特征很明显。Ipoh 其实挺像我家乡的，到处是山。
在路边房子后面一两百米就是群山。

前半段路很少商店，路过一个公园，我才在一个餐厅买了一杯可乐。进入市区又在7-11买了瓶装水。
郊区和城区的分界还是挺明显的。路上很多标志牌只有马来文，也有华文的（但是我没留意华文标志牌有没有马来文）。
但是很少英文。

路过 Sekolah Raja Perempuan Taayah  一所马来人女校的时候正好是课间休息，带着头巾的小姑娘们在走廊上。
她们看到了我，还有点雀跃，我向她们挥了挥手，有一群留意到我的学生也挥手回应了。当时我正好在听《无聊斋》，
有个在光线传媒工作的嘉宾聊到黄百鸣，所以这个场景让我想到《开心鬼》。

入住之后发现我整件T恤乃至裤头都湿透了，靠了一下枕头，连枕头都变潮了。睡一觉，然后起来吃晚饭。
* 饮食
第一顿是从机场出来的[[https://maps.app.goo.gl/ELfece8oCyLZ628T6][烧腊]]，里面的烧鸭是烟熏风味的，烧肉倒是没啥，配的酱料就是这边麦当劳常用的酸甜酱，我不喜欢。

晚饭吃了[[https://maps.app.goo.gl/KMyWVxoQbfP1XxGQA][德记炒粉]]，这个店在新加坡好像有分店，我点了他们招牌的月亮河和文冬芽菜。

所谓月亮河就是咸鲜口的湿炒河粉，中间窝了一个生鸡蛋。文冬芽菜就是豆芽。我常见的豆芽是细长的，但这边的文冬芽菜是粗短的。
汆烫之后，淋酱油（可能是店家自己调整过的酱油），上面洒葱花和胡椒粉。

第二天（18日）早餐就在酒店附近找了个早餐铺，这个早餐铺有点像新加坡的食阁，好几家档口开在一起，顾客随便坐，
到档口点餐或者等人过来招揽生意，饭菜做好了送上来。早餐吃了咖喱叉烧粉。

上午逛了几个景点，午饭没有正经吃，吃了碗豆花，还吃了一种忘记名字的马来小吃，服务员是个包着头巾说粤语的阿姨，
估计是嫁给马来人的华人。

晚上回来终于吃到[[https://book.douban.com/subject/25727391/][《马来西亚：爱上迷路》]]里面提到的芽菜鸡（其实就是芽菜和白切鸡）。芽菜前文已述，
白切鸡就令人感动：假如你在新加坡活得足够久，那么你对白切鸡的要求会下降到「没腥味就行」。
吃完晚饭出去转了一圈，去了附近一家本地精酿酒吧，喝了一种叫「陀地」的自酿甜酒（本来以为是本地品牌的啤酒）。
回来路上有个公园，公园里面有个长城咖啡，打着白咖啡的招牌。Ipoh 以白咖啡发源地著称，我不能不进去尝尝。
但白咖啡还是有点太甜腻了，跟速溶版本的区分不大[fn:1]。

19日早上有点尴尬，因为把高速流量用光了，Google Map 经常刷不出来，在流量恢复之前不敢走远。
早餐是几条街口的早餐店，吃了一碗擂茶。这里的擂茶其实是咸菜饭和一碗类似抹茶的茶汤。
饭是和着冬菜一类的腌菜一块的，咸鲜口，可能加了罗勒，茶汤浓稠，也带有咸味。如果饭里面再加鸡蛋或者火腿就更好了。

午饭在酒店附近的长城咖啡吃，没啥特色就按下不表了。

下午去逛完景点之后，去了黎紫书《流俗地》背景的[[https://t.me/danteslimbo/2940][组屋]]打了个卡，本来打算在旁边的南香茶餐厅吃顿饭的，无奈人家早早关店了。
于是我就在看完电影（为什么我会在 Ipoh 看电影，后文再表）之后，继续逛 Ipoh，在三德小学旁边有个夜宵一条街。
我在里面挑了一家烤鱼店，选了白蛤（水煮）和魔鬼鱼（酱烧）。魔鬼鱼在当地有个别名，但是我忘记了。酱烧是加虾酱，
但具体是烤完再加还是烤的时候就涂，我不太清楚，没看见老板烤。蛤不怎么样，感觉他们没有把蛤的泥沙清理干净。
酱烧魔鬼鱼让我很满足，我就喜欢咸鲜口的大块蛋白质。

顺带一提，我去到烤鱼店的时候，老板正跟一个人合影，如果我没有认错的话，应该是王俊棠，
但我只记得他在《栋笃神探》里面演大只佬，名字想不起来，所以我没有凑上去。

20日上午我就飞回新加坡了，出发之前去18日早上吃咖喱粉的早点铺里面吃了碟肠粉，肠粉本身倒没啥。
但是吃的时候，旁边的煤气罐让我提心吊胆，真是人越大越怂。
* 遇到的人
我并不是一个善于交际的人，看旅游文学很佩服作家们可以到处找人聊天。但我也绝非社恐，遇到健谈的人，
我还是可以像一个捧哏一样，陪着聊一段。

在 Ipoh 入住的酒店前台是个25岁的巴基斯坦小哥。我入住当天逛完回来，在酒店大堂狂灌水的时候，他非常热情地请我喝茶——立顿茶包。
于是我们就聊起来了，他来 Ipoh 6年了，但是再过一周就会回老家结婚，结完婚会休息一年，一年后再回来。
他在这边一个人上10点到晚上3点的班，如果住客有事，他就把前门扣上，去客房处理。他有个表弟还是堂弟在广东工作。
19号晚上，我跟他道别，祝他婚姻快乐。

18号从金宝古庙去南天洞的时候，在金宝英华学校[fn:2]上车，司机是一个华人大叔。大叔很健谈，祖上从福建过来，
年轻时去吉隆坡闯荡，又在新加坡干了19年装修公司，今年回来落叶归根开 Grab，家里四个孩子，三个上了大学，孩子在新加坡工作。
他说新加坡还是太赶太忙，不像这里清闲（Uncle 你让本大陆仔无言以对）。

* Footnotes
[fn:2] 这家学校全名 Anglo-Chinese School ，在 facebook 的[[https://www.facebook.com/iculturekampar/posts/%E5%AD%A6%E6%A0%A1%E7%AF%87%E9%87%91%E5%AE%9D%E8%8B%B1%E5%8D%8E%E5%AD%A6%E6%A0%A1%E8%BF%99%E6%89%80%E5%BB%BA%E7%AD%91%E9%A3%8E%E6%A0%BC%E7%8B%AC%E7%89%B9%E7%9A%84%E8%8B%B1%E5%8D%8E%E5%AD%A6%E6%A0%A1anglo-chinese-school-acs%E5%88%9B%E5%BB%BA%E4%BA%8E1903%E5%B9%B4%E4%BA%A6%E7%A7%B0%E4%B8%BA%E5%8D%AB%E7%90%86%E5%AD%A6%E6%A0%A1%E6%AD%A4%E6%A0%A1%E5%9D%90%E8%90%BD%E4%BA%8E%E9%87%91%E5%AE%9D%E5%9F%A0%E7%9A%84%E4%B8%BB%E8%A6%81%E9%81%93%E8%B7%AF%E5%8D%B3%E7%93%9C%E6%8B%89%E7%BE%8E%E6%A3%9A%E8%B7%AF/468079820701410/][图片]]挺图骗的，现场看比较破烂。 

[fn:1] 话说 Ipoh 著名的白咖啡品牌旧街场在市中心有开自己品牌的咖啡店，上午去喝过，挺时髦的咖啡店，各种咖啡饮料。 
