#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: reading
#+hugo_categories: reading
#+hugo_draft: false
#+description: 重新读了一次《阅微草堂笔记》。谈谈纪晓岚。
#+TITLE: 阅微草堂中的纪晓岚
#+author: Dantezy
#+date: 2024-06-06
最近把《阅微草堂笔记》重读了一次，上一次读应该是大学刚买了 Kindle3 狂读盗版书的时候。
这次读的版本是上海古籍出版社2016年出版的[[https://book.douban.com/subject/30185922/][全译本]]，没有注释，篇后附白话文全译。
每篇加了标题，后文会引用这些标题。
* 其书
《阅微草堂笔记》二十四卷：《滦阳消夏录》六卷、《如是我闻》四卷、《槐西杂志》四卷、
《姑妄听之》四卷、《滦阳续录》六卷，附录了纪晓岚长子纪汝佶的笔记六则。

这些笔记写作的时间不一，有些在纪晓岚在世的时候已经付梓，如果真的要认真考究，还是应该看每卷写作时间。
比如《姑妄听之》四卷，我怀疑这是跟蒲松龄打擂台的意思，因为纪汝佶学蒲松龄写小说，老纪挺不高兴的
（ ~后依朱子颖于泰安，见《聊斋志异》抄本， ( 时是书尚未刻。 ) 又误堕其窠臼，竟沉沦不返，以讫于亡。~ ）
而王渔阳的《戏书蒲生聊斋志异卷后》云：

#+BEGIN_CENTER
姑妄言之姑听之,

豆棚瓜架雨如丝。

料应厌作人间语，

爱听秋坟鬼唱诗。
#+END_CENTER

但我懒得考证，也就这样了，没有定论。

《阅微草堂笔记》在大众名气不如《聊斋志异》，不知道比《子不语》如何，但我偏偏只读过《笔记》和《子不语》。
因为《笔记》里面的篇章，大部分都很简单平直。就我印象，大部分故事纪晓岚都是立意先行，要宣扬他的那套价值观。
这对艺术水平当然有损，但更方便我去观察纪晓岚其人。
* 其人
如果要从《阅微草堂笔记》谈纪晓岚，首先要从脑海里面把张国立排除出去。一个历史人物有一部大流行的电视剧，
都不知道是福是祸，好处当然是扬名到更多人那里了，坏处就是电视剧那个形象跟本人偏离往往太大。
不过老纪人也死了，估计他不介意。《阅微草堂笔记》里面的纪晓岚当然就真实一点，「修辞立其诚」的自觉，纪晓岚还是有的。
但你不能太相信人的自觉，正如前文说的，这些笔记在纪晓岚生前就出版了，他当然会有「巧言令色」的部分。

单纯从《笔记》来看，纪晓岚这个人，信鬼神报应之说，这也没啥问题，前工业社会就是这样。问题是每个鬼神报应的故事，
老纪都有一套自己的解释，每个解释单独看都很自洽，但是如果连起来，到处矛盾。不得不感慨陈嘉映说古代中国人
「长于理性，短于理论」所言非虚。

老纪跟奴仆也非常不对付。《笔记》里面说道奴仆（不管是不是他自己家的），十有八九都是坏话（倒是有一二好话）。
比如《义犬四儿》一篇：

#+BEGIN_QUOTE
余在乌鲁木齐，畜数犬。辛卯赐环东归，一黑犬曰四儿，恋恋随行，挥之不去，竟同至京师。
途中守行箧甚严，非余至前，虽僮仆不能取一物。稍近，辄人立怒啮。一日，过辟展七达坂，
 ( 达坂译言山岭，凡七重，曲折陡峻，称为天险。 ) 车四辆，半在岭北，半在岭南，日已曛黑，不能全度。
犬乃独卧岭巅，左右望而护视之，见人影辄驰视。
余为赋诗二首曰：「归路无烦汝寄书，风餐露宿且随予；夜深奴子酣眠后，为守东行数辆车。」
「空山日日忍饥行，冰雪崎岖百廿程。我已无官何所恋，可怜汝亦太痴生。」纪其实也。
至京岁余，一夕，中毒死。或曰：「奴辈病其司夜严，故以计杀之，而托词于盗。」想当然矣。
余收葬其骨，欲为起冢，题曰「义犬四儿墓」；而琢石象出塞四奴之形，
跪其墓前，各镌姓名于胸臆，曰赵长明，曰于禄，曰刘成功，曰齐来旺。
或曰：「以此四奴置犬旁，恐犬不屑。」余乃止。仅题额诸奴所居室，曰「师犬堂」而已。

初，翟孝廉赠余此犬时，先一夕梦故仆宋遇叩首曰：
「念主人从军万里，今来服役。」次日得是犬，了然知为遇转生也。
然遇在时阴险狡黠，为诸仆魁，何以作犬反忠荩？岂自知以恶业堕落，悔而从善欤？亦可谓善补过矣。
#+END_QUOTE
在他眼里仆人还不如狗。又如《蔡季实殿撰》一条：

#+BEGIN_QUOTE
蔡季实殿撰有一仆，京师长随也。狡黠善应对，季实颇喜之。忽一日，二幼子并暴卒，其妻亦自缢于家。
莫测其故，姑殓之而已。其家有老妪私语人曰：「是私有外遇，欲毒杀其夫，而后携子以嫁。
阴市砒制饼饵，待其夫归。不虞二子窃食，竟并死。妇悔恨莫解，亦遂并命。」
然妪昏夜之中，窗外窃听，仅粗闻秘谋之语，未辨所遇者为谁，亦无从究诘矣。
其仆旋亦发病死。死后，其同侪窃议曰：「主人惟信彼，彼乃百计欺主人。
他事毋论，即如昨日四鼓诣圆明园侍班，彼故纵驾车骡逸，御者追之复不返。
更漏已促，叩门借车必不及。急使雇倩，则曰风雨将来，非五千钱人不往。主人无计，竟委曲从之。不太甚乎！奇祸或以是耶！」
季实闻之，曰：「是死晚矣，吾误以为解事人也。」
#+END_QUOTE
这仆人做事当然不厚道，但就这点罪行，折算下来最多有期徒刑（没准还有缓刑），在纪晓岚眼里就是值得冚家富贵的大罪，
着实有点过分。当然我这么说，是以今度古，按[[https://book.douban.com/subject/4167959/][《清代社会的贱民等级》]]，纪晓岚不把这些奴仆当人，也合法理。
但显然他其实拿这些下人没办法嘛，不然何至于整个「义犬墓」「师犬堂」，真有办法他把这四个家奴撵跑得了，
师犬堂这事情最可笑，按清朝的识字率，估计他的家奴都未必识字，偏偏不敢搞造像，只能上块牌匾精神胜利，端的是人菜瘾大。

《阅微草堂笔记》最大的主题，还是纪晓岚的「核心价值观」，总结下来就是「忠孝节烈」：
#+BEGIN_QUOTE
匪今斯今，振古如兹矣。惟不失忠厚之意，稍存劝惩之旨。见《东楼鬼》一则。
#+END_QUOTE

「别嫌疑，明是非，定犹豫，善善恶恶，贤贤贱不肖，存亡国，继绝世，补弊起废」当个古代儒生，谁不想 cos 一下孔子呢。
最大的问题在于纪晓岚选的有些故事，灾难性堪比李密跟王伯当举例子。

比如《奇节异烈之女》一条：
#+BEGIN_QUOTE
又闻诸镇番公曰：「明季，河北五省皆大饥，至屠人鬻肉，官弗能禁。有客在德州景州间，
入逆旅午餐，见少妇裸体伏俎上，绷其手足，方汲水洗涤。恐怖战悚之状，不可忍视。
客心悯恻，倍价赎之；释其缚，助之著衣，手触其乳。少妇艴然曰：『荷君再生，终身贱役无所悔。然为婢媪则可，
为妾媵则必不可。吾惟不肯事二夫，故鬻诸此也。君何遽相轻薄耶？』
解衣掷地，仍裸体伏俎上，瞑目受屠。屠者恨之，生割其股肉一脔。哀号而已，终无悔意。惜亦不得其姓名。
#+END_QUOTE
这个故事我看下来觉得很神经，但纪晓岚在这里「惜亦不得其姓名」那种吟哦赏玩的态度，很恶心。
我们都知道 porn 这种东西，就是把动物性赤裸裸地展示在人面前的一种比较低俗的娱乐方式。按 Merrian Webster 词典：
#+BEGIN_QUOTE
pornography:

  3. the depiction of acts in a sensational manner so as to arouse a quick intense emotional reaction.
#+END_QUOTE
按这种定义，纪晓岚写这种节烈故事，可以称为「名节之 porn」。
反正这次读完《阅微草堂笔记》，我明白了不但自由放荡会激发欲望，道德名教这种东西也能激发人的欲望。
而且在道德名教的名义下，激发的欲望更加显得奇形怪状。

前面说过，我是现代人，价值观念上跟清代人不同(我看纪晓岚是迂腐不堪的虫豸，他看我也是无父无君的禽兽)。
但真的像我上面说，你整这么奇葩的故事，符合「中庸之道」吗？

不过在这里要帮老纪说点话，按《清史稿》：
#+BEGIN_QUOTE
二年，复遷禮部尚書。疏請婦女遇強暴，雖受污，仍量予旌表。十年，協辦大學士，加太子少保。卒，賜白金五百治喪，諡文達。
#+END_QUOTE

但我们继续就书论书，因为我们毕竟是活在一个意识形态跟物理现实永远保持不一致，永远靠认知失调来维持运转的世界。
在《笔记》里面，纪晓岚伦理学还有个问题：它非常不自洽。

同样是再嫁这种情况，《妾再嫁》一条里面，他批评再嫁的妾：
#+BEGIN_QUOTE
余谓再嫁，负故夫也；嫁而有贰心，负后夫也。
#+END_QUOTE
到后面《私祭》一条，对私下祭祀前夫的再嫁妾，他的评价变了：
#+BEGIN_QUOTE
此之谓欤！虽琵琶别抱，已负旧恩，然身去而心留，不犹愈于同床各梦哉。
#+END_QUOTE
更离谱的是《不忘旧情》一条，再嫁的妾（甚至有个还是狐妖）照顾前夫的孩子和寡妇，都能获得好评：
#+BEGIN_QUOTE
此之谓欤！虽琵琶别抱，已负旧恩，然身去而心留，不犹愈于同床各梦哉。
#+END_QUOTE
就让人感觉微妙，想前夫是不行的，拜祭可以，帮助前夫的族人值得赞赏。非常微妙的道德观，宗族大于夫妻嘛。

王渔阳《城北偶谈》记了一个《张巡妾》的故事：
#+BEGIN_QUOTE
徐藹，字吉人，會稽諸生。年二十五，得瘕疾，痛不可忍，年餘，瘕能作人言。
瀕死時，見一白衣少婦問曰，君識張睢陽殺妾事乎？君前生為睢陽，吾即睢陽之妾也。
君為忠臣，吾有何罪？殺之以饗士卒。吾尋君已十三世矣，君世為名臣，不能報復，今甫得雪吾恨。
言訖，婦不見，藹亦隨逝。庚申在京師，其門人範思敬說。
#+END_QUOTE
这个故事王本人不见有什么立场，但是老纪看到了，写了一条《著书当存风化》：
#+BEGIN_QUOTE
渔洋山人记张巡妾转世索命事，余不谓然。其言曰：「君为忠臣，我则何罪，而杀以飨士？」
夫孤城将破，巡已决志捐生。巡当殉国，妾不当殉主乎？古来忠臣仗节，覆宗族糜妻子者，不知凡几。
使人人索命，天地间无纲常矣。使容其索命，天地间亦无神理矣。王经之母含笑受刃，彼何人乎！
此或妖鬼为祟，托一古事求祭飨，未可知也。或明季诸臣，顾惜身家，偷生视息，造作是言以自解，亦未可知也。
儒者著书，当存风化，虽齐谐志怪，亦不当收悖理之言。
#+END_QUOTE
非常不把人当人。

当然我再强调一次，我是个现代人，很多观念跟清代人不同，而且我还活着，多少欺负老纪是个死人了。
假如我能跟纪晓岚面对面谈一下，他会怎样反应？

可能是：「我！纪文达，大清协办大学士加太子少保，四库全书总编辑，轮得到你这乱臣贼子来教训我？
来人，拉他去菜市口。」

有啥好说的。
* 结语
我最近沉迷一档播客《无聊斋》，里面的主持教主刘旸就提到过《阅微草堂笔记》（比如449期
《文化有限，进来听劝，这本书真的不看不行了》）。

无论怎么样吧，把《阅微草堂笔记》当故事书看，还行，有些故事特有意思，如《伟丈夫》一条：

#+BEGIN_QUOTE
李千之侍御言：某公子美丰姿，有卫玠璧人之目。雍正末，值秋试，于丰宜门内租僧舍过夏。
以一室设榻，一室读书。每晨兴，书室几榻笔墨之类，皆拂拭无纤尘；乃至瓶插花，砚池注水，
亦皆整顿如法，非粗材所办。忽悟北地多狐女，或藉通情愫，亦未可知，于意亦良得。
既而盘中稍稍置果饵，皆精品。虽不敢食，然益以美人之贻，拭目以待佳遇。一夕月明，潜至北牖外穴纸窃窥，冀睹艳质。
夜半，闻器具有声，果一人在室料理。谛视，则修髯伟丈夫也，怖而却走。次日，即移寓。移时，承尘上似有叹声。
#+END_QUOTE

非常有幽默感。

另外要把这本书作为清代文化风俗材料看，也可以。我也是读这书才知道古代妓女其实是可以、且会结婚的（见《好色身亡》一条）。
虽然可能不如《子不语》，但是本书在性癖上的记录，也是非常多元的，如《蓄妾》一条：
#+BEGIN_QUOTE
郭石洲言：河南一巨室，宦成归里，年六十余矣。强健如少壮，恒蓄幼妾三四人；至二十岁，则治奁具而嫁之，皆宛然完璧。
娶者多阴颂其德，人亦多乐以女鬻之。然在其家时，枕衾狎昵，与常人同。
或以为但取红铅供药饵，或以为徒悦耳目，实老不能男，莫知其审也。后其家婢媪私泄之，实使女而男淫耳。
有老友密叩虚实，殊不自讳，曰：「吾血气尚盛，不能绝嗜欲。御女犹可以生子，实惧为身后累；欲渔男色，又惧艾豭之事，为子孙羞。
是以出此间道也。」此事奇创，古所未闻。夫闺房之内，何所不有？床笫事可勿深论。惟岁岁转易，使良家女得再嫁名，似于人有损；
而不稽其婚期，不损其贞体，又似于人有恩。此种公案，竟无以断其是非。
戈芥舟前辈曰：「是不难断，直恃其多财，法外纵淫耳。昔窦二东之行劫，
必留其御寒之衣衾、还乡之资斧，自以为德。此老之有恩，亦若是而已矣。」
#+END_QUOTE

这一条，商务印书馆的[[https://book.douban.com/subject/1018360/][《性心理学》]]收录在附录里面，仔细一看，这老头还是个双性恋，不得不说，牛。
