#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: travel
#+hugo_categories: log
#+hugo_draft: true
#+description: 特意组织的吉隆坡观鸟之旅。
#+author: Dantezy
#+date: 2026-04-07
#+TITLE: 吉隆坡游记
三月中蹭同事车去了新山(Johor Bahru)，再上一次去马来西亚已经是2024年的事了，见[[https://dantezy.xyz/posts/ipoh-2024/][《Ipoh 游记》]]。
忘记啥时候想整一个吉隆坡观鸟之旅，本来开斋节就想去，不过那天是周六，没有长周末[fn:1]，
于是改成4月3日[fn:2]出发。

* 观鸟
老实说，以前我旅游都是漫无目的，纯「为旅游而旅游」。现在观鸟上瘾之后，
确定旅游目的地时我会考虑有哪些方便的观鸟地点。当然这次吉隆坡之旅纯为观鸟。
我对旅游规划的建议只有两点：1. 看文化遗产[fn:3]；2. 看鸟，或者看其他独特的动植物（学点博物知识的好处就来了）。

总的来说这趟观鸟之旅，我不是很满意，总共只加新了8种鸟，有些鸟还不是很确定具体的鸟种。
这次计划了五个观鸟点。4月4日去了

1. [[https://ebird.org/checklist/S319117424][Perdana Botanical Gardens]]
2. [[https://ebird.org/checklist/S319123898][Taman Rimba Kiara]]
3. [[https://ebird.org/checklist/S319131524][Taman Tasik Permaisuri]]

这三个都是城市公园，所以安排在同一天，遗憾的是吉隆坡跟新加坡距离还是太近了，
这种城市公园的鸟种跟新加坡差别不大，所以这天虽然跑了三个地方，但是加新只有一种：
牛背鹭(Eastern Cattle-Egret, Ardea coromanda)，当然我在这里拍到很清晰的夜鹭。
Taman Tasik Permaisuri 北面的湖里面有一棵树和一丛竹子，树上满是彩鹳、苍鹭、夜鹭和草鹭。
彩鹳虽然罕见，但近照真不合我的审美——好吧咱直说吧，彩鹳真的很丑。
竹子上是住满了小白鹭和牛背鹭。不知道它们为什么这样混居。繁殖期的小白鹭饰羽长出来了，
很好看，而且我发现它们喙根部跟头部连接的地方是粉红色的，真的很漂亮[fn:4]。

这几个城市公园给我的印象就是：1. 鹊鸲比新加坡更常见（然而它是马来西亚 ebird 敏感鸟种）；
2. 白胸翡翠是这里最常见的翠鸟，新加坡最常见的是白领翡翠——都不是普通翠鸟哈哈哈。
为什么鹊鸲更常见，可能是因为吉隆坡城市化不如新加坡，爪哇八哥对鹊鸲的优势没那么大吧。

4月5日去了 Sungai Congkak Recreational Forest，Sungai 马来语，河、江的意思。
一条小河贯穿了整个森林。我回来整理列表才知道它已经不属于吉隆坡，而属于 Selangor 。
这次旅游我最期待的地方就是这里，确实它也是我收获最大的地方：https://ebird.org/checklist/S319179210

当天我去得很早，07:32出发，08:13到达。到达的时候天已经阴了，小红书推荐在 Skytrex 下车，
但我没留意，离 Skytrex 还有一公里多，路上没有什么行人，我不能不想起寂静岭，
还有各种杀人越货的剧情。不过下车不久我就在一棵树上面看见三只大盘尾(Greater Racket-tailed Drongo, Dicrurus paradiseus)，
当然这在新加坡其实也能看到，只是求而不得。然后我一路进去，下雨了，幸好我走得快，
走到 Skytrex 入口雨才下大，不然我就玩完了（实际上相机和望远镜已经湿了）。

在 Skytrex 入口看了半个多小时《革命的年代》，等到雨小了，我就冒险出发。
这场雨对这次行程影响很大。我要靠树枝的异动来判断是不是有鸟活动，但是现在下了雨，
我就无可奈何了，很多动静都是树叶上的雨水落下搞出来的。
另外不知道是不是因为相机湿了，还是单纯空气湿度大了，我拍到一只绿叶鹎，
但是细节拍得不清楚，Merlin 说是小绿叶鹎，但我实在不太相信自己的运气，
记录就写 Leafbird sp 算了。树林里面有一片草地，旁边靠近树林一侧有一座废弃的房子，
靠近大路的一边有四五棵我不知道品种的树。我来回经过的时候都在这几棵树上看到没见过的鸟，
但是基本没法拍到清晰的照片。直到写这篇博客的时候我还是心有不甘。

我怀着一种「五月渡泸，深入不毛」的心情一路走到雨林最深处再走回来，
进去的时候已经九点多，河边已经热闹起来。
很多马来西亚人把车停在河边，铺块垫子，就在河边野餐，有些人还会穿上泳衣跳进河里，
也有人在河边钓鱼。很多是一家大小来的，也有朋友组团来的，这是我羡慕的生活。

在我从雨林深处回来，就快到我前面说的草地的时候，我瞥见了路边有一个大鸟，
这就是我此行最大的收获：一只雌性花冠皱盔犀鸟(Wreathed Hornbill, Rhyticeros undulatus)，
它就在路边的树上一动不动，任由我在路上换不同的角度拍个不停。它是易危鸟种，
问了一下亮哥，中国只有云南少数地方有。能碰到算我运气爆棚了。

但我还是觉得不满意，因为这是我纯运气碰到的，不是我找到的。而且这么一片森林，
我只加新了7种鸟，还有两种不是很确定。所谓「人心苦不知足，既得陇，又望蜀」，
说的就是我。永远不满意，所以就永远不开心咯。得改，真的。

最后一天计划去 Shah Alam Botanical Gardens，但失算了，没开门，应该是因为 hari raya?
又去了一次 Taman Tasik Permaisuri ， 但也没有看到传闻中的鸟导大叔，更看不到猫头鹰。
时也命也！

* 电影

* 书店

* 本地人、闲逛与一些感想

* Footnotes
[fn:4] 对常见的鸟，birder 会称之为「菜鸟」 或者 trash bird(见 The birding dictionary)。
对此我比较矛盾，一方面吧，确实很多鸟看得多了，别说举相机，望远镜我都懒得举。另一方面，
即使是很常见的鸟，也会有很有意思的时候——我就拍过白眉黄臀鹎吃某种蜂的照片。

[fn:3] 去年天津之旅的游记见我的[[https://t.me/danteslimbo/5456][频道]]，亲眼得见独乐寺十一面观音那种震撼真可谓一眼万年。

[fn:2] 实际上我的旅行计划起止会受假期和机票价格约束，唉，什么时候我才能不用斟酌机票价格，
只看出发时间呢？

[fn:1] 新加坡公共假期来源多样，比如 Good Friday 就是复活节前的星期五，这种公共假期能自然形成长周末。
