#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: reading
#+hugo_categories: reading
#+hugo_draft: false
#+description: 终于通读了一次《聊斋志异》，论小说，蒲松龄当然力压纪晓岚，但槽点就少很多了。《聊斋》适合随手一翻「任意东西」地读。
#+TITLE: 聊斋笔记若干
#+author: Dantezy
#+date: 2024-08-07

这次读的是人民文学出版社2020年出版的《[[https://book.douban.com/subject/30151678/][全本新注聊斋志异]]》。

* 1

蒲松龄的在《聊斋自序》里面自称是「松」，有点奇特。

刚想说蒲松龄不像纪晓岚，什么故事都要寻个因果报应的解释，《瞳人语》一篇他就忍不住「异史氏曰」。不过总的来说他还是比较收敛。

* 2

《尸变》：简单的恐怖故事，四个人求宿，没有空房，主人让住在儿媳妇停尸的房间，晚上尸变，女尸把三个人害死，有个睡不踏实的人逃出来，逃到早上才避过一劫。

搁纪晓岚，这个儿媳妇肯定是不孝顺公婆的，这四个人要不就是平事做坏事，要不就是前世做坏事，活下来这个人估计就是早上做了点好事。他会非寻个解释不可。蒲松龄老实很多，只写下来，啥都不多说。

* 3
在读《聊斋志异》，但是吐槽的情况很少，因为蒲松龄的评论，你最多觉得他喜欢说教，走封建道德的一套，没有不近人情，所以没啥好吐槽的。

* 4
其实李翰祥都拍《聂小倩》了，为啥他不按《侠女》来一篇呢？《聊斋》这篇侠女，有三角恋、双性恋、Trans（狐变人）、剑仙、偷情、未婚生子、封建礼法，元素太丰富了

* 5
《九山王》和《遵化署狐》两篇几乎都是同样的故事：人害一家狐狸族灭，幸存的狐狸报复回来。

搁纪晓岚，他肯定得叨逼叨狐狸怎么先冒犯人，人做得有点过分，但是狐狸你不是能预知未来吗？怎么会不知道人心呢？

* 6
《伏狐》一篇，古代 Furry 控啊。

* 7
《鸲鹆》，鸲鹆就是八哥，这个故事跟《王成》有点像。故事里面卖八哥的人对这八哥也够意思——当然假如我有一只能指挥我做事的八哥，我也会对它讲义气。

* 8
《黄九郎》， 我一直想从笔记小说里面探究一下清代人对同性恋的看法，感觉上跟我看待 porn 差不多：不会觉得这是好事，但也不会觉得是什么大事，总体而言，接近 not even wrong，但是这篇最后，蒲松龄写了一段四六来表达他不赞同肛交——这多少有点滑稽，同时我在想，如果单纯柏拉图式恋爱，同时形婚，对蒲松龄和纪晓岚来说，这样的同性恋跟非同性恋，大概一点区别都没有啊！

他老人家还特意写了一篇《肛交赋》，服了：
#+BEGIN_QUOTE
男女居室，为夫妇之大伦；燥湿互通，乃阴阳之正窍。迎风待月，尚有荡检之讥；断袖分桃，难免掩鼻之丑。
人必力士，鸟道乃敢生开；洞非桃源，渔篙宁许误入？
今某从下流而忘返，舍正路而不由。
云雨未兴，辄尔上下其手；阴阳反背，居然表里为奸。
华池置无用之乡，谬说老僧入定；蛮洞乃不毛之地，遂使眇帅称戈。
系赤兔于辕门，如将射戟；探大弓于国库，直欲斩关。
或是监内黄鳣，访知交于昨夜；分明王家朱李，索钻报于来生。
彼黑松林戎马顿来，固相安矣；设黄龙府潮水忽至，何以御之？
宜断其钻刺之根，兼塞其送迎之路。
#+END_QUOTE
* 9
《老饕》 我的朋友洋葱老师告诉我《聊斋》以人名为褒贬：善者有名有姓有号，恶者但称某而已。这篇故事里面的邢德，出身绿林，无论他作为主角还是作为配角，干的事都不地道：想打劫老弱，不仁；看不出对手身怀绝技，不智，当然邢德最后有个改过自新的结尾（不知道是真的改了还是蒲松龄硬拗的）。
* 10
《连城》 这个故事到乔生割肉救人只求连城一笑的部分我挺喜欢的，充满相逢意气为君饮的浪漫。

另外本篇反派王化成（按现代改编，他应该会跟马文才同等待遇）也有名有性。
* 11
《商三官》， 男人无路用其一。

《小二》， 男人无路用其二。

《庚娘》， 男人无路用其三。

不过虽然《小二》里面的丁生也没有什么用，但确实他把小二从白莲教里面带了出来，还是做对了一件事，他起码扮演了象棋里面将帅的作用——虽然无能，但是重要，哈哈哈。另外《小二》里面乔生对小二的爱慕，缘起自他们一起上学——不知道这是什么性质的教育机构。
* 12
《宫梦弼》， 这篇小说写法上很有意思，题为《宫梦弼》但是宫梦弼直接出场的时间不多，第一段就杀青了。但是影响了前半部分故事，但后半部分好像跟他完全没有关系，这我就不理解了。
* 13
《驱怪》

#+BEGIN_QUOTE
「黄狸黑狸，得鼠者雄」：出处待查。狸，狸猫。雄，雄杰。此语犹今俗谚：黑猫白猫，捉住耗子便是好猫。
#+END_QUOTE

这注释笑死。
* 14
《念秧》，这个层层递进的骗局，颇有 IJN 九段决战的风格。
* 15
《酒狂》，喝酒误事就算了，阴间老舅帮平了事，居然欠他冥钱！这人不行。
* 16
《封三娘》，这个故事有个美好的百合开头，但有个令人不快的结尾。
* 17
《荷花三娘子》

这个故事其实分了两段，三娘子是后半段的女主角。我反而更喜欢前半段：有个叫宗湘若的读书人，看到一个女人跟人野战，然后邀请这个女人到他的别墅交欢（你看我用词多文雅）。后来身体逐渐不行，因为这个女人是狐妖。老宗求一个到他们村的番僧打救。番僧给他一个法器，收了狐妖，但是呢
#+BEGIN_QUOTE
夜深，女始至，探袖中金橘，方将就榻问讯。忽坛口飕飗一声，女已吸入。家人暴起，覆口贴符，方欲就煮。宗见金橘散满地上，追念情好，怆然感动，遽命释之。
#+END_QUOTE
这一段细节我觉得真的很动人。
* 18
《窦氏》，好惨一故事，但很适合拍成恐怖电影，或者做恐怖故事。
* 19
《聂政》，蒲松龄扬聂政贬荆轲，多少有点以成败论英雄了。
* 20
《冤狱》

讲完这个杀人故事之后，蒲松龄出来 cos 太史公说：
#+BEGIN_QUOTE
余尝谓为官者，不滥受词讼，即是盛德。且非重大之情，不必羁侯。
#+END_QUOTE
这就借题发挥了，本文里面都出人命官司了你来扯这个淡。你老人家自己一生主业就是当幕僚，清代地方政府怎么运作你老人家不清楚吗？不过其实纪晓岚也没有好多少，算是个时代局限性吧。
* 21
《甄后》，不知道这是蒲老还是清代人民群众的风气，曹操曹丕两父子挺倒霉的，一人一顶绿帽子扣上来。
* 22
《诗谳》，谳(yan 第四声）：审判定案。这一篇非常适合改编成电影剧本。
* 23
《佟客》

这篇后面附有一篇小故事，短小精悍一波三折，我挺喜欢的。
#+BEGIN_QUOTE
邑有快役某，每数日不归，妻遂与里中无赖通。一日归，值少年自房中出，大疑，苦诘妻。妻不服。既于床头得少年遗物，妻窘无词，惟长跪哀乞。某怒甚，掷以绳，逼令自缢。妻请妆服而死，许之。妻乃入室理妆；某自酌以待之，呵叱频催。俄妻炫服出，含涕拜曰：「君果忍令奴死耶？」某盛气咄之。妻返走入房，方将结带，某掷盏呼曰：「咍，返矣！一顶绿头巾，或不能压人死耳。」遂为夫妇如初。此亦大绅者类也，一笑。
#+END_QUOTE

这里蒲松龄是笑这个快役耳朵软，从我这个现代人看来，这个快役挺可爱的。无论出轨对一个人来说算不算事，我觉得都不应该闹出人命。
* 24
《王司马》

张大春有一篇《吴大刀》，后半段完全从这篇《王司马》脱胎而来。

此外，张大春还改了一篇《王者》。
* 25
《苗生》
#+BEGIN_QUOTE
此等文只宜向床头对婆子读耳，广众中刺刺者可厌也。
#+END_QUOTE

今日社交媒体上的东西，大都是这类「只宜向床头对婆子读」，豆瓣友邻尤甚。
* 又

** 《快刀》
#+BEGIN_QUOTE
盗从之刑处，出刀挥之，豁然头落。数步之外，犹圆转而大赞曰：​「好快刀！」
#+END_QUOTE
这不就是郭德纲相声《艺术的技术》里面杀于谦的刀吗？
** 《土偶》
#+BEGIN_QUOTE
令曰：「闻鬼子无影，有影者伪也。」抱儿日中，影淡淡如轻烟然。
#+END_QUOTE
「这孩子，魂淡！」——又是一段相声。

** 《张鸿渐》
#+BEGIN_QUOTE
大凡秀才作事，可以共胜，而不可以共败：胜则人人贪天功，一败则纷然瓦解，不能成聚。
#+END_QUOTE
讽刺知识分子太准确了！

** 《一员官》
#+BEGIN_QUOTE
人皆言斯世不可以行直道；人自无直道耳，何反咎斯世之不可行哉！
#+END_QUOTE
