#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: mygo anime
#+hugo_categories: anime
#+hugo_draft: false
#+description: 我自己也想不到，今年居然会有一部动画切实地影响到我。BanG Dream! It's MyGo !!!!! 这部作品对我的冲击不亚于六祖惠能听到《金刚经》。
#+author: Dantezy
#+date: 2023-11-12
#+TITLE: 善逝从来非本相，或者，应无所住生是心
我自己也想不到，今年居然会有一部动画切实地影响到我。BanG Dream! It's MyGo !!!!! （以下简称 MyGo，指代乐队名称的时候会用 MyGo!!!!!）这部作品对我的冲击不亚于六祖惠能听到《金刚经》。
* 缘起
我知道 MyGo 之前，Soyo 女士（长崎素世，以下简称 Soyo）已经完成了她的[[https://www.bilibili.com/video/BV1SP41147qu][惊天一跪]]。尽管我不看这部动画，但是我还是听到 Soyo 的名字然后上萌娘百科查了一下（同时也问了以下我的朋友陈工）。

在某个吃汉堡王的夜晚，我点开了 MyGo。一个 Meme 可以吸引我注意，但很多时候，我看个开头就会觉得「只看那个出圈的梗就好了」，
然后弃坑。
* 感情变化
开始看 MyGo 的时候，我觉得这就是一部 PTSD 互助者的故事：MyGo!!!!! 乐队的五个人基本心理都不太健康，除了猫（要乐奈[fn:1]，以下简称猫）都有某种心理创伤。
我当时想，叔叔我呀，自己的心理都不太健康，为什么要看一群小姑娘发癫。

转折来自第8话（Soyo 女士在这一话贡献了年度名场面：惊天一跪[fn:3]）。

《坛经 行由品》里面说五祖给六祖讲经
#+BEGIN_EXAMPLE
祖以袈裟遮围，不令人见。为说《金刚经》，至「应无所住而生其心」，惠能言下大悟「一切万法不离自性」。
#+END_EXAMPLE

我看到这一话也有这种感觉，MyGo 只是讲组乐队和青春伤痛的故事吗？远远不止啊，它讲了一群因果相续三毒缠身的人，每个人都有自己的执着，每个人都困在自己的执着里面。
但是要走出执着，还是要靠自己。在这个时刻，我也感觉我悟了。
* 破我执
一直以来我的睡眠都不好，睡眠时间不足、入睡时间不规律。早上没精神，晚上睡不着。整个陷入一种焦虑的轮回中。
* Footnotes
[fn:3] 简单为没有看过 MyGo 的朋友介绍这个名场面的由来，祥子（丰川祥子，以下简称祥子）组建了乐队 Crychic，Soyo 和睦（若叶睦，以下简称睦）都是其中成员。
但是在一个大雨滂沱的傍晚，祥子过来说她要退出 Crychic（这个事件是整个故事的起点，至于原因涉及严重剧透，不作叙述）。
Crychic 分崩离析，在此之前，Crychic 完成并演出了[[https://zh.moegirl.org.cn/zh-hans/%E6%98%A5%E6%97%A5%E5%BD%B1][《春日影》]]。

时过境迁之后，Soyo 跟 Tomori（高松灯，以下简称 Tomori，原 Crychic 成员）等人组建了新的乐队，在乐队的 live 上，
演奏了《春日影》。睦带着祥子看 live ，听到《春日影》之后，崩溃痛哭逃出演出现场（至于原因，涉及剧透）。在台上目睹一切的 Soyo
也大受打击，在演出结束之后，表演了她带来的第一个年度名场面：[[https://www.bilibili.com/video/BV19F411y7FA][なんで春日影やったの？！！]][fn:2]

之后 Soyo 一直尝试用手机联系祥子，结果被拉黑。无奈之下她只能压迫睦去给她祥子的地址，亲自去祥子面前解释，不为所动的祥子甩手而去，Soyo 情急之下抓着祥子的手跪下哀求对方重新回到乐队，
随后祥子给出了她的金句：[[https://www.bilibili.com/video/BV1Sm4y1T782/?spm_id_from=333.337.search-card.all.click][你这个人，满脑子都是自己呢。]]
 
[fn:2] Soyo 女士贡献两个年度级名场面，对推广 MyGo 功不可没啊。 

[fn:1] 其实猫是不是心理正常也很难说，我之前在教会做义工的时候就碰到一个小男孩，完全不跟人沟通，
上课的时候自己想做什么就做什么，稳定的血压提升器。
