#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: mygo anime
#+hugo_categories: anime
#+hugo_draft: false
#+description: 我自己也想不到，今年居然会有一部动画切实地影响到我。BanG Dream! It's MyGo !!!!! 这部作品对我的冲击就像六祖惠能听《金刚经》听到「应无所住而生是心」。
#+author: Dantezy
#+date: 2023-11-12
#+TITLE: 善逝从来非本相，或者，应无所住而生是心
我自己也想不到，今年居然会有一部动画切实地影响到我。
BanG Dream! It's MyGo !!!!!（以下简称 MyGo，指代乐队名称的时候会用 MyGo!!!!!）这部作品对我的冲击就像六祖惠能听《金刚经》，
听到「应无所住而生是心」而大悟一样。

* 剧情梗概
转学来到羽丘的千早爱音遇到了有点孤僻的少女高松灯。为了融入新学校，爱音想和灯一起组乐队。之后偶遇了月之森中学的长崎素世，
以及花咲中学的椎名立希和要乐奈，五个女孩子，其中四个各怀心思组成了一个乐队 MyGo!!!!!，磕磕碰碰地走向未来。
这是 MyGo 这部动画明面上的故事线。

实际上，高松灯、长崎素世和椎名立希曾经跟丰川祥子和若叶睦组成过另一个乐队 Crychic, 在一个大约滂沱的傍晚，丰川祥子突兀地告知众人，
自己要退出 Crychic。Crychic 分崩离析（悲鸣！）。这件事给众人留下难以磨灭的伤痕。

巧合的是，几乎不再跟往日队友联系丰川祥子刚好跟千早爱音和高松灯同校，在 MyGo!!!!! 走向自己的舞台时，丰川祥子也开始走向不同的道路，
组建了乐队 Ave Mujica （估计是第二季的剧情）。

* 因缘和合
我的睡眠一直都有问题。我睡觉的时间不定，躺在床上常常久久难以入睡。每天都是在疲惫中开始，疲惫中结束。在床上辗转反侧的时候，
是我最空虚沮丧的时候，我感觉自己被困在「轮回」之中。

刚开始看到的时候，我还在看《大乘百法名门论讲记》和《金刚经讲义》[fn:1]，看到第8集的时候，我忽然有种顿悟：
其实 MyGo 讲述了一个众人陷于执着不得解脱的故事。

第8集诞生了一个名场面：[[https://www.bilibili.com/video/BV1SP41147qu][素世下跪]]。这个名场面我不在这里叙述，说出来没有意思，不明白前因后果估计我说了也不明白。
这个剧情，其实有很复杂的因果。祥子毁灭了 Crychic，这是一切的因。直接的过就是素世内心在创伤（当然不止她一个人受伤）。
素世一直执着于祥子，执着于重建 Crychic。这个过程里面她自己很受伤，她也伤害若叶睦（在这个片段之前她把所有过错都归咎
若叶睦，以此利用睦的愧疚感来问出祥子的住址）。但是祥子自己也很执着。她执着于自己的自尊。
从退团开始到她听到《春日影》破防、素世不断发消息给她试图解释，一年多时间过去了，但凡她解释一下，局面都不会这么尴尬。
但是她偏不[fn:2]。

素世这件事导致了新乐队再次面临分崩离析的危机。很有轮回的感觉：第一次公演之后，一个成员忽然要退团了。
新乐队本身就各怀异心（或者说各有各的魔障）。千早爱音想出风头（她自己在英国留学过不了语言关赶紧回来，
主打一个平生进退如飙风）。高松灯本身就内向孤僻，Crychic 散伙给她的伤害其实是最大的，她的执着就是「一辈子的乐队」。
椎名立希简单很多，她就是想和高松灯在一起，但她还是要暗搓搓跟姐姐和祥子较劲。只有要乐奈，这个野猫一样的女人，
像风一样难以捉摸（说实话，乐队的危机主因基本都不是她，但是在「阻止乐队走向危机」这点上她是一点都不干啊）。

执着既是因也是果。在第8话到第11话，乐队的危机最直接的因就是素世对祥子（或者说对昔日 Crychic）的执着。
她的离去再次伤害了本身就脆弱的灯。但是灯也很执着，如果灯不执着的话，立希倒是可以应付这个危机：她去找素世问清楚原因，
知道对方组建乐队的根本目的是重建 Crychic 之后，几乎马上找来好友海玲过来顶替素世贝斯手的位置。
也就是说椎名立希如果可以绕开灯，她能解决这个危机。问题是绕不开。

在这种进退维艰的局面里面，还是灯走出了最重要的一步，她追回了离队的爱音，自己定了 live 场，在上面声嘶力竭地呐喊出自己的诗句
（可以想象要走出这一步对她这种性格的人来说是多么不容易[fn:3]）。爱音拉回了素世、要乐奈拉回了立希。乐队终于获得了自己的名字：
MyGo !!!!![fn:4]
* 六界因缘无了痕
看 MyGo 的过程里面，我的睡眠问题居然奇迹般得到解决了，我可以稳定在两点左右入睡，然后在八点左右醒来。
当然我不是说这是一部动画的缘故。这个问题的解决非常微妙。

#+BEGIN_QUOTE
三身果报自凡根，六界因缘无了痕。善逝从来非本相，枯荣生灭尽空门。
#+END_QUOTE

这其实不是正经的佛偈，是霹雳布袋戏里面帝如来的诗号。只是我在读佛教书籍的时候经常会想起这四句诗号。

因为看 MyGo 的时候，我同时在看佛教的书籍，所以在第8集之后，我想到从因缘、业果和执着的角度去看 MyGo 后面的剧情。
剧中人的困境恰好与我本人的困境相呼应：陷入一种类似轮回般不得解脱的境地。而剧中人勇敢地破去执着，解去困境，
让我产生信心和勇气。我想这是解决我睡眠问题复杂又微妙的原因。
* 应无所住而生是心

* Footnotes
[fn:4] 对我这种地海迷来说，真名的重要性不言而喻。 
[fn:3] 当然初华和睦的助攻也是很必要的！ 
[fn:2] 涉及剧透，但是看完第一季全部剧情，我觉得祥子当时退出 Crychic 确实是因为遭遇她自己无法处理的危机。
她后面的不解释，只是说是能力问题，道德上不太好指责。但我想到一个比喻：
你在大街上忽然被一辆坦克追杀，你操起反坦克导弹自卫，手忙脚乱误伤了路人，这没办法。但被你误伤的路人可不会客气。
[fn:1] 都没有看完，《大乘百法名门论》本身就很枯燥，它就是罗列了「百法」。《金刚经讲义》好一点，
但是江居士讲得太细了。

