#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: sci-fi fiction
#+hugo_categories: fiction
#+hugo_draft: false
#+description: 总算写出来的小说，或者说，我的科幻点子集合。假如宇宙就是轮回不息的循环？有办法打破这个轮回吗？
#+author: Dantezy
#+date: 2025-09-29
#+TITLE: 涅磐
* 一
当瞿鹊[fn:1]族到达银河系第三旋臂的行星时，上面的文明已经被毁灭。这颗行星的卫星不知为何坠落在这颗行星上[fn:2]，
曾经昌盛一时的文明就此湮灭，散布在这个星系中零星的殖民地在失去了母星的支持后, 也走向灭亡。

瞿鹊族搜罗了这个文明的信息，留下了伊们的信标，然后重新踏上太空流浪之途。

直到瞿鹊族也失落在茫茫太空之后，伊们曾经留下的信息才被长梧族收到。
长梧族是一个身被金属的种族，能用薄膜将恒星系包住，使恒星的能量全部留在星系之內，因为内外能量的隔绝，
薄膜外也成了接收宇宙信息的好地方。

瞿鹊的信息，首先是重复三次一长一短的脉冲，
然后是一次短脉冲，一次长脉冲，一次短脉冲一次长脉冲，再来是两次长脉冲……
经过多段信息的比对,长悟族确认了开头三次脉冲是在用二进制表示三个连续的2[fn:3]。
这三个连续的2也是一个分隔符,随后的脉冲是二进制的0到31。

随后对瞿鹊族文字虽然更费工夫，但最终还是顺利破译，
以恒星为引警、流浪在星际之间的瞿鹊族一心冀望在星海中找到另一个可以对话的智慧种族，
然而总是失望，伊们只能找到文明的才遗，到最后，伊们无奈地悲鸣：我们只是光速的囚徒。

长梧族也明白这个道理，但伊们有个更不祥的消息：宇宙正在坍缩，而瞿鹊族的信息发出时，宇宙还在膨胀。

最后长悟族倾尽整个文明最后的岁月,才捕获了九颗黑洞,进行了伊们称为雕刻黑洞的计划。

这是第一纪。

* 二

罔两[fn:4]族是硅基文明，生活在伊们世界的海洋中。
当伊们收到与宇宙年龄一致的引力波时，伊们敏锐地意识到里面的含义：
一长一短不断重复的脉冲, 这是一串循环的2。

2是唯一的素偶数，从宇宙始源时传来的循环的2让罔两族明白到，宇宙曾经湮灭，又在湮灭中重生，
在上一个湮灭的宇宙中，有一个种族领悟到了这个真理

囿于航天能力，罔两族未能突破自己的星系，但伊们用自己即将燃尽的恒星作为燃料，把所有信息发送了出去。
最后被景族接收到。

景族从白矮星起源，伊们的几何学从球面几何开始，伊们无从得知信息何以穿越宇宙的死亡再重生,
伊们把罔两族的信息重新编码，向宇宙广播。可惜太空寂寥，没有回音。

景族后来倾注心血在亚原子层级的雕刻刻中，
希望这些粒子能在宇宙湮灭之后,依然能保存足够的信息，伊们也曾尝试在白矮星中雕刻出独特的结构，
希望如在宇宙重生之后发出类似的引力波信息。

这是第二纪。

* 三

景族雕刻在白矮星中的信息未能形成可观测的引力波，但伊们用雕刻的亚原子粒子侥幸保留下来。

右师族，或者说右师[fn:5]，是藻类形成的集体意志，在信息交换的过程中，它们，或者说它，
发现了景族留在亚原子中的信息，景族留下了雕刻亚原子粒子和白矮星的技艺。
右师惊叹宇宙的浩瀚，并为如何留下信息而苦思冥想。

右师族无法摆脱对恒星的依赖，最终选择长悟族同样的技术路线，将整个恒星系包裹起。
以恒星为引擎驱动整个星系在宇宙中前进。

最终，右师选择了雕刻黑洞的方式，保留了景族留下全部信息。这是所有文明的幸运。

这是第三纪。

* 四

秦失族[fn:6]和右师族类似，都是由群居生命組成的集体智慧。不同的是，
泰失的个体是一种黑色带角质蛋白外壳的生命体，六足，不完全变态[fn:7]。
一个族群构成了一个智慧生命，伊们战胜了星球上更为高级靠胎儿繁衍的物种,主宰了伊们所在的行星。

秦失强大的繁衍欲望迫使伊们走向太空，它们渴望让自己的卵蛸遍布整个宇宙，
在探索太空的过程中，伊们认识到，光耀伊们星系的太阳，居然是一个智慧生命，其名为老聃。

老聃保存了自宇宙初始以来的信息，知道宇宙的轮回，也告知了秦失一族，秦失族不以为意，
个体的生命朝生暮死，聚集成群体智慧能延绵不绝，即使目睹宇宙走向没落，也是无可奈何但能坦然面对的事情。

在扩张的过程中，伊们还希望能找到老聃的匹俦，可惜的是，老聃是独一无二的存在，
无以为报的秦失只好从宇宙中搬来其他恒星延续老聃的生命。

得益于此，老聃在宇宙的尽头前成为了一个黑洞，伊在粒子中雕刻了过去的历史，
又在自己雕刻中出创世之初的引力波。当宇宙新一轮的轮回,
曾属于伊的物质将会激发一串创世之初的引力波，回荡在新生的宇宙中，宣告过去的轮回。

这是第四纪。

* 五
列子族[fn:8]诞生在宇宙边沿一颗超新星，伊们以电磁波的形式存在。

在起源超新星爆炸的时候，列子族乘着爆炸抛射的高能电磁波，幅射到邻近的恒星。
部分列子族安居于新的恒星中，但也有部分列子族会主动改造所在恒星，让它爆发新的电磁风暴——
然后列子族会乘着新的爆发，到达新的恒星。就这样，列子族占领了整个宇宙。

自然，伊们得知了老聃保存下来的信息，获释了宇宙的轮回。

尽管个体寿命比秦失族在外部看来更短, 宇宙之于列子一族几乎是无穷无尽，
但列子族依然投入应对宇宙的寂灭。伊们想到，可以进一步雕刻黑洞和粒子，
在创世之后的新宇宙中，列子族将会重生。

在宇宙寂灭的前夕，列子族点燃了千万恒星。

最后的列子族籍由这些恒星的爆发进入黑洞中，完成最后的工作并祈求在新的宇宙中重生。

这是第五纪。

* 六
鲲[fn:9]族诞生在星尘当中，伊们在宇宙虚空中激游。

列子族的期望落空了，伊们未能在宇宙中重生，但鲲族发现了伊们的子遗，
仔细研究了列子族遗留在亚原子粒子的信息后，
伊们认为这是一个很有创意的想法，但伊们在重新塑造电磁波生命形式这一步失败了。

鲲族采取了更激进的方法，伊们先把自已化身为信息生命体，
只需要把信息本身保存下来，整个生命体便被保存下来了。

转化之后的民族为自己起了一个新名字鹏。

这是第六纪。

* 七
鹏族在新宇宙重生之后，开始思考一个问题: 有办法阻止宇宙的轮回吗?

伊们联合了新生宇宙的杰出的智慧生命逍族，尝试在宇宙中构建超大型的黑洞，
让这些黑洞成为宇宙中的钉子，稳定宇宙的空间结构。

然而即使是庞大的黑洞，在坍缩的宇宙面前，也徒呼奈何。逍族拒绝了鹏族将伊们信息化的好意，
在这个宇宙的终点前，两族道别，走向各自的命途。

这是第七纪。

* 八
鹏族反思到：宇宙是动态变化的，无法将它固定下来。所以在新宇宙里面，伊们想到新的方法。

在宇宙还在扩张的时期，鹏族收集星系到宇宙中心，堆积成巨大的黑洞，以此抑制宇宙的扩张。
等到宇宙收缩到一定的程度，在爆破这些黑洞，让宇宙重新膨胀。
这个宇宙里面跟逍族相似的生命遥族也加入到这个宏大的计划里面。

但是宇宙扩张和收缩处于一个脆弱的平衡之中，宇宙在膨胀收缩若干次之后，这个平衡还是被打破了，
鹏族再次无奈面向宇宙的毁灭。但这一次，逍族有了一个更每秒的主意，伊们跟鹏族合而为一

这是第八纪。

* 九
鹏族与遥族融合的新种族名为游族。在上一个纪元尽头，遥族想到，既然宇宙的毁灭无可避免，
何不把整个宇宙塑造成一个生命？

游族在创世之初开始改造宇宙，以星系为细胞，以引力波传递神经信号，宇宙一张一缩，既是呼吸，
也是言语。

于是这个宇宙成为了一个生命，当伊获得自己的意志，在无尽的虚空中一张一缩，发出自己的信号。
伊收到了其他宇宙的共鸣。

这是第九纪以及后来无数的纪元。

* 后记
这篇小说最初的[[https://t.me/danteslimbo/5289][点子]]是：假如我们无法突破光速，永远困守在银河系的的一角里面，
而宇宙又在不断循环，那么会有怎样的故事。

我不擅长写故事，所以很多点子最后都无疾而终，但是受 [[https://en.wikipedia.org/wiki/All_Tomorrows][All Tomorrows]] 和《庄子》影响，
我写成了这样一篇「东西」。无论如何，它都是一篇小说，即使再糟糕，也比没有写出来好。

有点搞笑的是，全篇都在用《庄子》的人物命名，但是标题确实来自佛教的涅磐——我确实想不到更好的名字了。

全篇写了九个纪元，因为「一是数之元，九是数之极」[fn:10]，有了开头的设定，
想好最后的结尾，又确定了章节数目，只需要安排每个章节的进展即可，这是一个讨巧的方式。

其中我最喜欢第四纪，一个满布蟑螂的宇宙是我的恶趣味，最后蟑螂推来恒星报答一颗恒星，
让这颗恒星变成黑洞，最后把信息传递到新的纪元，这恰好就是《养生主》秦失吊老聃之后的一段：

#+BEGIN_QUOTE
指穷於为薪，火传也，不知其尽也。
#+END_QUOTE

本文中第三人称使用无性别指向的伊，这是受 Ursula K. Le Guin 的影响。

#+BEGIN_QUOTE
「他」可以涵盖「她」，但「她」不能涵盖「他」的用法显示了一种观点，
蕴含着极大的社会道德暗示。然而我们又不是非要用人称代词 he 不可——我们明明有 they ，
为何不用呢？
#+END_QUOTE

中文做起来还更容易，因为「伊」是现成的，还可以说是学鲁迅。

2025年9月29日夜初稿（不过其实这个稿件我用 git 管理着，完全可以看到改动历史）。

* Footnotes
[fn:10] 基本不会有人懂的[[https://www.bilibili.com/video/BV191421972S][霹雳布袋戏梗]]。

[fn:9] 后面的名字都来自《逍遥游》，就不一一备注了。

[fn:8] 《庄子·逍遥游》 ，列子御风。

[fn:7] 其实就是蟑螂。我也曾经想过如果蟑螂以族群为单位形成智能，会有怎样有趣的故事。

[fn:6] 《庄子·养生主》，老聃死，秦失弔之，三号而出。

[fn:5] 《庄子·养生主》，公文轩见右师而惊曰。

[fn:4] 《庄子·齐物论》，罔两问景曰。下景同。

[fn:3] 这个想法我不敢居功，是小时候读过的一篇科幻小说提出的，外星人向外散播一种小球，
这种小球的大小跟原子的比例约等于一个中等恒星跟这个小球的比例，小球里面有一个表示2的图案。
地球的科学家因此知道这是一个智慧种族：因为这个种族显然知道数论。

[fn:2] 显然，这是我们的地球。我曾经想过，如果月球偏离了轨道在一百年左右的未来撞向地球，
人类会怎样应对。我悲观地认为人类会先打一场或若干场大战。

[fn:1] 《庄子·齐物论》，瞿鹊子问乎长梧子。下长梧同。
