#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: reading 科幻小说 思想史
#+hugo_categories: reading
#+hugo_draft: true
#+description: 整理一下2020年读过的书。读过的书仿佛一根线，将记忆串联起来。
#+author: Dantezy
#+date: 2022-09-06
#+TITLE: 个人阅读史2020
* 2019年的余绪
2020年开始的时候，我所在的公司 SMI 倒闭了[fn:1]，我留在深圳的出租屋里面。有点不安，但也没有很恐慌[fn:2]，按部就班开始计划找工作。春节临近，我呆着深圳的出租屋里。
当时的出租屋是南山一个公寓，不到三十平方米，步行8分钟可以到公司。隔板隔开客厅和卧室，有独立卫生间。没有煤气炉，我也没有买电磁炉，[[https://wzyboy.im/][wzyboy]] 送我一个烤箱。
但日常还是以外卖、附近的小食店为主。

卧室基本就是床，但还是有空间放一张书桌。我在书桌上准备面试（无非是刷刷 leetcode 和面经）。客厅有我买的懒人沙发，房子自带的沙发上摆了我从多抓鱼买来的书。准备面试之余，
我就在客厅里面看书，玩 Switch。

一月初的时候，新冠疫情初起，当时没有太特别的感觉，除了觉得湖北官员颟顸，反应迟钝，根本想象不到这场疫病影响会如此深远。当时从深圳先回广州，还在 WP 那里住了一晚，
去参加朋友的婚礼。从广州回老家，又参加了
** 冯内古特
年初读完了两本冯内古特：《没有国家的人》和《如果这都不算好，什么算？》。

2019年我在多抓鱼上买了一堆冯内古特，当时读了很多。冯内古特和我在桃园的居所连系在以前。想起那堆书我就会想起在南山的日子。很可惜读这两本书的时候 SMI 已经“执笠”了。
** 《时间回旋》
这本科幻小说的妙处在于它描述的宇宙图景，没有爱、没有恨，人类是故事的中心但只是宇宙的微尘。

有一个出色的点子并不能保证写出科幻小说。于宏大的想象中进行细腻的叙述更见功底。《时间回旋》做到了这一点。
* 失业居家时期
SMI 倒闭之后我回到老家，刚好在疫情爆发，我在老家住了一段时间。这段时间读的书都跟这段时期的回忆紧密相连。疫情和失业都令我忧心。

2020年1月23日绝对是足以记入史册的一天。2020年的时候我并不是每天都记日记，所以有些记忆会有偏差。大约是封城前后的一次晚餐，我舅舅打电话过来告诉我们，因为疫情，
今年亲戚聚餐就不搞了。但无论如何，武汉封城之后，疫情无可争议地占据了我的视线。但我不得不承认，找到一份工作才是我最关注的。
** 《罪与罚》
我在1月24日重读完这本书。

我高中的时候读完《罪与罚》，但是印象不深，我都忘记拉斯柯尔尼科夫的妹妹不是嫁给检察官——那监察官不是什么好鸟。其实这次重读，印象也没有很深。
或者我应该像伊坂幸太郎笔下的杀手蜜柑一样随身携带每天重读。除了拉斯柯尔尼科夫，我只记得拉祖米兴（如果拉斯科尔尼科夫愿意接受他的帮忙，也不至于杀人被流放）。

关于这本书有个有趣的注脚，我当时用 Kindle Unlimited 借阅，很久之后我想重读的时候发现书库里面找不到这本书，当时勃然大怒：“我记得我在武汉封城前后读过《罪与罚》的！？”
我以为 Amazon 删了我的书，过了很久才想起当时是借阅的。
** 《叫魂》《杀千刀》《大门口的陌生人》
这三本都是汉学家写了中国历史著作。
** Kubernetes in Action 《人月神话》
要看点技术想的书籍保持状态。
** 《古代的职官》
* 深圳求职时期
** 《暗杀教室》
** 《编程之美》《Linux/Unix 系统编程手册》《操作系统导论》
* 西乡独居

* Footnotes
[fn:2] 最近我们公司丑闻不断，连续裁员。甚至我觉得比2020年一月的时候更焦虑。 

[fn:1] 关于它为什么倒闭，是另一个故事。 
