#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: log religion singapore
#+hugo_categories: log
#+description: 来新加坡之后跟基督教后期圣徒教会有一定接触。
#+author: Dantezy
#+date: 2022-05-24
#+TITLE: 新加坡观察：基督教后期圣徒教会(LDS)

* 楔子
新加坡实在太中国了，一点都没有出国的感觉[fn:1]。你让我买纪念品，我都不知道买什么好。

刚到新加坡时，我就想好好了解这个国家，当时找了很多新加坡的书来看，大部分都读不下去，唯独[[https://book.douban.com/subject/35114099/][《寻迹狮城》]]这本游记写得还算有趣，全书以作者横穿新加坡的徒步旅程为经纬，穿插新加坡的历史和现状，同时表达作者的观点。

几经波折读下来[fn:2]，作者有些数据已经过时（2016年135天没有犯罪举报，但我来这半年光是暴力犯罪就不下四起），有些印象已经落伍（新加坡人不读书，实际上就我观察，新加坡地铁上读纸质书的人和 Kindle 使用者都比深圳的多）。虽然作者跟新加坡高层谈笑风生，但是对他的结论，我还是半信半疑，这种文人式观察得出来的结论还是有点浅。

所以我想，尽信书不如无书，不如自己来亲自记录一番，即使不是高屋建瓴，起码也是亲身经历。

为什么第一篇写的是 LDS 呢？首先新加坡其实很中国，一个人基本可以用中文在这个国家纵横，但在宗教方面跟中国很不同，新加坡教会密度更高，而且传教士们可以公开上街传教。买特产也希望买真的是当地才有的产品吧。其次除了公司同事，跟我接触最多的就是 LDS 的传教士（后面会详细说），所以我决定先谈谈 LDS[fn:3]。

* 缘起
我的同事 Robin 在 meetup 上看到 LDS 提供免费的英语课，时间是工作日晚上，但是可以另外找时间上一对一的英语课，所以怂恿我去。虽然我当时没有马上去，但还是留心了。某个周日无事，我就过去 LDS 在 Newton 那边的教堂，路途有点远，大约一个小时。这个教堂有华语崇拜。

周日的崇拜是10点开始的，我到教堂的时候已经10点多了，在门口遇到一个信徒，她热情地为我带路，并把我介绍给传教士认识。当天我还留下来跟他们上主日课。

* 传教士

大部分时间，我都是跟 LDS 的传教士接触（卫理公会的信徒会更活跃）。LDS 的传教士有男有女，男性传教士是 Elder, 女性传教士是 Sister，他们会戴一个胸牌，上面写 Elder/Sister XXX 。男性传教士一般会穿白衬衫黑色西裤，打领带。女性传教士会穿得更休闲。通常传教士都是两人一组行动，但是他们会经常轮换。

Lim 和 Tayler 是我最早认识的传教士（就是上文说的第一次崇拜认识的传教士），Lim 是本地华人， Tayler 来自美国（我忘记哪个州了）。他们的汉语都很流利。Lim 很年轻，我记得他大概25、26的样子。Tayler 也很年轻，但是我对他印象不深（他汉语说得很流利）。第一次崇拜的主日课之后他们加了我 whatsapp, 之后我们会每周在 Zoom 上面开会（或者是上课）。他们教我祈祷。

大概过了两周，我记不清 Lim 被调去 Sembawang，另一个叫 Manirajan 的传教士继续跟我接触（我忘记那个时候 Tayler 是不是更早轮换了）。 Manirajan 肤色黝黑，是本地印裔传教士。Manirajan 和另一个叫 Benson 的传教士搭档。他们给我上过两次英语课，纠正了我 v 和 th 的发音（但我后来不想去了）。Manirajan 和 Benson 给我上英语课的时候告诉了我很多教会的信息：比如传教士是没有薪水的；传教士每六个月就要轮换到不同的教区；传教士们每周只有周一下午可以自由活动，其余时间都要做传教工作。
他们一般是两个人共用一台手机。我猜教会不太愿意传教士跟信徒有太亲密的私人关系。Benson 也告诉我，他们希望人们是因为主来教会，不是因为传教士来教会。

Benson 最后跟 Stein 搭档，他们是跟我接触最久最稳定的传教士。 Benson 是田纳西州白人，在杨百翰大学（就是 LDS 的教会大学）读大一，高，而且瘦。Stein 肤色略黑，有亚裔血统（如果我没有记错的话），但我忘记他来自哪个州了，刚高中毕业。Benson 和 Stein 跟我在 Zoom 有时候会邀请其他信徒参加我们的 Zoom 会议。

他们给我讲了 LDS 的救恩计划、LDS 的世界观[fn:4]、摩西十诫、赎罪与悔改、受洗。4月时他们跟我说，要不要考虑受洗，我说我现在还不相信上帝，所以不能受洗。他们说没所谓，我们可以制定一个计划，按部就班，到时候你应该就能接受上帝，接受洗礼。最后他们给我定了在5月28日接受洗礼。
5月初的时候，我们不再在 Zoom 开线上会议，改在线下见面。Stein 兴致勃勃地给一张日历，上面标注我在受洗之前的日程。之后他们还在 whatsapp 上联系我，告诉我受洗的时候会问的问题，以及我应该如何回答。但正是这种殷勤让我吃不消，因为我从来都不打算受洗。
5月22日是星期日，我本来想去教会亲自跟他们说明，但是睡过了，所以我在 whatsapp 上跟他们说了。从回复来看他们吃惊，也焦急，回复了很长的一段。我答应下个周二跟他们见面再当面解释清楚。
这次见面我们约在 City Hall，就在新加坡河旁边。我们就坐在河边谈，气氛没有我想象那样僵硬（我想象的画面里面他们会气急败坏且失望，而我则充满愧疚）。我们愉快地聊关于信仰的话题。我说我始终不能相信上帝，虽然有点冒犯，但是我是接受无神论教育长大的，我不能接受一个人格化的上帝，我相信光速不变，相信宇宙从大爆炸而来，人类从单细胞生物进化而来（我终于提起勇气问他们如何看待进化论）。Stein 跟我说，你相信科学，没关系，但是神创造了一切，他也创造了科学。就算宇宙是从大爆炸而来，但这也是神创造的，神也创造了进化论。话都说到这份上了，我还有什么可以说的呢？我只能坦言我实在无法相信上帝，我很乐意跟你们见面，讨论信仰的问题（主要是我想练习英语口语），但我怕浪费你们的时间。他们表示不会，只要你继续保持一种开放的心态就好。于是我继续跟他们（传教士们见面）。

劳动节放假（对，新加坡也放劳动节假期）的时候，LDS 组织了一次单身派对（但是派对上大部分男女比我父母的年龄都要大），Benson 和 Stein 邀请我过去参加。教会组织我们跳舞，第一种舞步的名字我忘记了，我跟着领舞，舞步笨拙。但是 Benson 跳得很好，他告诉我这是田纳西州的舞步。Stein 没有跟我们一起跳舞，他在下面给家人写邮件。他告诉我，等他完成传教的工作，他会回去，也许会进大学（他才高中毕业），然后找工作，结婚。

河边聚会的两周后，Stein 和 Benson 邀请我去另一个教堂，我去了（因为这个教堂离我家更近），那个教堂用英文做崇拜，我认识了传教士 Grey，之前 Stein 和 Benson 介绍我认识的一个台湾信徒蔡弟兄也在，我们聚在一起聊了一会，我向 Grey 坦诚我不信教。之后加了他 whatsapp.

又过了一周，两个女传教士 Hall 和 Winder 加了我 whatsapp。我这才知道原来 LDS 有女传教士。


* Footnotes
[fn:4] 描述这个世界的时候，他们画了一个 LOVE ：L 表示从灵体世界降生，O 表示地球，人类接受考验和地方，V 表示死后等待耶稣最终审判的地方，E 表示三种不同的天堂，对，没有地狱，只有不同的天堂，非常星巴克。虽然我不信他们这一套，但是他们这个 PPT 技能实在不错。

[fn:3] 以后我还会写一下卫理公会。

[fn:2] 我当时还想跟随作者的路线，一章一章重走他走过的路，去了一趟大士关卡就放弃了。 

[fn:1] 万里他乡身是客，我觉得我在哪里都是客人，片叶不沾身。好处是没有什么留恋和牵挂，坏处就是因为没有留恋和牵挂，显得轻飘飘，不实在。
