#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: zh/posts
#+hugo_auto_set_lastmod: t
#+hugo_tags: log 
#+hugo_categories: log
#+description: 记录一些关于戒酒的想法。
#+author: Dantezy
#+date: 2022-09-05
#+TITLE: 戒酒记
* 缘起
4月8日去 CMGS 家烧烤，喝得一谈糊涂，之后有宿醉的感觉，于是在4月12日我决心戒酒。

当然这不是我第一次喝到宿醉，也不是我第一次宿醉之后下决心戒酒。不过这是目前戒酒的最长记录（146天）。
* 戒酒之后的感觉
我在大三开始喝酒，最初是啤酒，后来跟陈老师一起喝伏特加。我喝酒没有什么讲究，也谈不上品酒（因为味觉迟钝）。喝醉的次数不少，
所幸没有在喝醉的时候做过什么过分的事情。就算喝到吐也能吐到厕所里面（不过2020年初在广州喝完酒，
回我朋友住处的时候跟门卫差点吵起来）。

总的来说，戒酒之后生活没有什么变化。想喝酒的时候也有，不是很强烈。刚好在通过[[https://t.me/reorx_share][孟骁的 channel]] 看到这篇文章
[[https://p0werdown.com/posts/drink-alcohol][《狂卖 1400 亿的致癌饮品，每年害死 83 万中国人》]]（非常标题党的标题）。里面说到：
#+BEGIN_QUOTE
从数据上看，996、婚姻、育儿、房贷等压力，早就让这届年轻人无法告别酒精，大概也是同样的原因，也让他们不得已只能「微醺」。
正如父辈们下班后喜欢小酌一杯那样，只是现在年轻人们有了更好的选择。
#+END_QUOTE
我自己喝酒没有什么理由，高兴的时候会喝，不开心也会喝，失眠的时候会喝一点，读侦探小说读到侦探喝酒自己也会倒上一点。
社交方面，我基本做到了「只跟朋友喝酒」，这得益于 IT 行业喝酒的人少，在餐桌上强迫别人喝酒的人更少（这可能只是我走运碰到）。
我不觉得喝酒可以消愁，反而宿醉让我更难受。

其实我也不知道为什么戒酒这么容易，可能是以为我本身酒瘾就不大。尽管如此，我还是把戒酒列入我2022年个人成就里面，
虽然跟2021年的个人成就减肥成功相比，这个成就的含金量不高（不喝酒比节食简单得多），但多少是个成就。可能 LDS
的传教士们会觉得是上帝引领我这个迷途的羔羊——但其实不是。

正如喝酒对我的损害不明显一样，戒酒之后的生活没什么变化：我不靠喝酒社交（其实我基本没有社交）；入睡一如既往地困难且无规律。
总体来说没啥改变——当然可能从概率来看，我死于肝癌的风险降低了。
